// @flow

export const RESPONSIBLE_SQUADS = {
  coachingAndPerformance: 'coaching-and-performance',
  corePlatform: 'core-platform',
  corePlatformII: 'core-platform-2',
  leagueOperations: 'league-operations',
  performanceMedicine: 'performance-medicine',
  reporting: 'reporting',
};
export const UNMATCHED_ROUTE = 'unmatched-route';

export type ResponsibleSquads = $Values<typeof RESPONSIBLE_SQUADS>;
export type RouteMapping = { route: string, squad: string };

const responsibleSquads: { [key: ResponsibleSquads]: string[] } = {
  [RESPONSIBLE_SQUADS.corePlatform]: [
    '/forms',
    '/forms/form_answers_sets',
    '/forms/form_templates',
    '/forms/form_templates/settings',
    '/forms/my_forms',
    '/forms/form_answers_sets',
    '/assessments',
    '/alerts',
    '/athletes',
    '/athletes/availability',
    '/athletes/availability_report',
    '/calendar',
    '/settings/organisation/edit',
    '/settings/questionnaire_templates',
    '/documents',
    '/media/documents',
    '/media/videos',
    '/messaging',
    '/private_forms',
  ],
  [RESPONSIBLE_SQUADS.corePlatformII]: ['/user_profile/edit', '/users'],
  [RESPONSIBLE_SQUADS.leagueOperations]: [
    '/league-fixtures/discipline',
    '/league-fixtures/discipline/profile',
    '/league-fixtures',
    '/league-fixtures/reports',
    '/events_management',
    '/fixture_finder',
    '/scout-schedule',
    '/scout-schedule/reports',
    '/registration',
    '/registration/organisations',
    '/registration/squads',
    '/registration/profile',
    '/registration/organisations',
    '/registration/squads',
    '/registration/profile',
    '/registration/requirements',
    '/registration/complete',
    '/registration',
    '/administration/officials',
    '/settings/officials',
    '/settings/officials/new',
    '/administration/additional_users',
    '/administration/additional_users/official/new',
    '/administration/additional_users/scout/new',
    '/administration/additional_users/match_director',
    '/administration/additional_users/match_monitor',
    '/settings/athletes',
    '/settings/kit-matrix',
    '/settings/imports',
    '/administration/scouts',
    '/administration/scouts/new',
    '/administration/imports',
  ],
  [RESPONSIBLE_SQUADS.coachingAndPerformance]: [
    '/benchmark',
    '/benchmark/league_benchmarking',
    '/benchmark/test_validation',
    '/planning_hub',
    '/planning_hub/settings',
    '/planning_hub/coaching_library',
    '/planning_hub/events',
    '/planning_hub/league-schedule',
    '/planning_hub/league-schedule/reports',
    '/planning_hub/league-schedule/requests',
    '/growth_and_maturation',
    '/growth_and_maturation/assessments',
    '/growth_and_maturation/assessments/baselines',
    '/workloads/games',
    '/workloads/training_sessions',
    '/reviews',
    '/recruitment',
  ],
  [RESPONSIBLE_SQUADS.performanceMedicine]: [
    '/medical',
    '/medical/rosters',
    '/medical/athletes',
    '/medical/documents',
    '/medical/procedures',
    '/efile',
    '/efile/inbox',
    '/efile/sent',
    '/efile/contacts',
    '/stock_management',
  ],
  [RESPONSIBLE_SQUADS.reporting]: [
    '/athletes/reports',
    '/home_dashboards',
    '/dashboards',
    '/dashboards/templates',
    '/analysis/graph/builder',
    '/analysis/dashboard',
    '/analysis/benchmark_report',
    '/analysis/template_dashboards',
    '/analytics/injury_risk_contributing_factors',
    '/analysis/athletes',
    '/analysis/squad',
    '/report',
  ],
};

export default responsibleSquads;
