/* eslint-disable flowtype/require-valid-file-annotation */
export const athleteData = () => [
  {
    id: '33925',
    full_name: 'Jon Doe',
    availabilities: [
      'unavailable',
      'unavailable',
      'unavailable',
      'medical_attention',
      'medical_attention',
      'medical_attention',
      'available',
      'available',
      'available',
      'available',
    ],
  },
  {
    id: '4343231',
    full_name: 'Charles Baston',
    availabilities: [
      'unavailable',
      'unavailable',
      'unavailable',
      'medical_attention',
      'medical_attention',
      'medical_attention',
      'available',
      'available',
      'available',
      'available',
    ],
  },
  {
    id: '43242',
    full_name: 'Jordon Harpe',
    availabilities: [],
  },
];

export const expandedAthleteData = () => ({
  id: '33925',
  full_name: 'Jon Doe',
  absences: [
    {
      availabilities: [
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'reason_1',
        'reason_1',
        'reason_1',
        'reason_1',
        'reason_1',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
      ],
      duration: '5 days',
      end: '6 Aug 2019',
      id: 1234,
      start: '2 Aug 2019',
      title: 'International Duty',
      type: 'absence',
      events: [
        {
          duration: 477,
          event_date: '2018-08-22T01:00:00+01:00',
          id: 27926,
          injury_status_id: 1,
        },
      ],
    },
  ],
  illnesses: [],
  injuries: [
    {
      availabilities: [
        'status_1',
        'status_1',
        'status_1',
        'status_1',
        'status_1',
        'status_2',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
        'available',
      ],
      duration: '19 days',
      end: null,
      id: 12345,
      start: '27 Jul 2019',
      title:
        'Ankle Apophysitis/ avulsion fracture to calcaneus ( Severs Dx) [Left]',
      type: 'injury',
      events: [
        {
          duration: 5,
          event_date: '2018-08-22T01:00:00+01:00',
          id: 27926,
          injury_status_id: 1,
        },
        {
          duration: 2,
          event_date: '2018-08-24T01:00:00+01:00',
          id: 27928,
          injury_status_id: 2,
        },
      ],
    },
  ],
});
