// @flow

export const mockGame = {
  id: 1,
  background_color: '#FFFFFF',
  created_at: '2021-10-14T09:07:23Z',
  end_date: '2021-10-16T12:32:00Z',
  competition: { id: 1, name: 'Champions League' },
  duration: 90,
  local_timezone: 'Europe/Dublin',
  mass_input: false,
  name: null,
  notification_schedule: {
    id: 471,
    scheduled_time: '2021-10-16T13:32:00+01:00',
    created_at: '2021-10-14T10:07:27.000+01:00',
    updated_at: '2021-10-14T10:07:27.000+01:00',
  },
  number_of_periods: 2,
  opponent_score: 0,
  score: 9,
  opponent_squad: { id: 1, name: 'U19', owner_name: 'Chelsea' },
  squad: {
    id: 1,
    name: 'U19',
    owner_name: 'Manchester United',
    owner_id: 1337,
  },
  opponent_team: { id: 1, name: 'Chelsea' },
  organisation_team: { id: 1, name: 'Team A' },
  round_number: null,
  event_location: {
    name: 'Dublin',
  },
  rpe_collection_athlete: true,
  rpe_collection_kiosk: true,
  start_date: '2021-10-16T11:02:00Z',
  surface_quality: null,
  surface_type: null,
  temperature: null,
  type: 'game_event',
  updated_at: '2021-10-14T09:07:23Z',
  venue_type: { id: 1, name: 'Home' },
  weather: null,
  mls_game_key: 'mls-12324',
  game_status: 'awaiting_officials',
  access_request_accessible: true,
  access_request_time_valid: true,
  match_monitors: [
    {
      id: 1,
      firstname: 'Jonny',
      lastname: 'Evans',
      fullname: 'Jonny Evans',
      username: 'jevents',
      date_of_birth: '1990-01-01',
      role: 'jevans',
      email: 'jonny@monitor.com',
      mobile_number: null,
      created_at: '2025-03-28T10:59:19Z',
      locale: 'en',
      is_active: true,
      avatar_url: null,
    },
    {
      id: 2,
      firstname: 'Richard',
      lastname: 'Dunne',
      fullname: 'Richard Dunne',
      username: 'rdunne',
      date_of_birth: '1985-01-01',
      role: 'RichardDunne',
      email: 'richard@monitor.com',
      mobile_number: null,
      created_at: '2025-03-05T14:38:28Z',
      locale: 'en',
      is_active: true,
      avatar_url: null,
    },
  ],
};
