// @flow
// Documentation: https://kitmanlabs.atlassian.net/wiki/spaces/ENG/pages/352125059/WIP+Feature+Flag+Tracking+and+Management
import medicalFeatureFlags from '@kitman/modules/src/initialiseProfiler/modules/utilities/medicalFeatureFlags';
import reportingFeatureFlags from '@kitman/modules/src/initialiseProfiler/modules/utilities/reportingFeatureFlags';

const featureFlags = {
  ...medicalFeatureFlags,
  ...reportingFeatureFlags,
  'date-picker-allow-null-constraints': 'date-picker-allow-null-constraints',
  'update-time-picker': 'update-time-picker',
  'hide-calendar-settings-cog': 'hide-calendar-settings-cog',
  'optimized-calendar': 'optimized-calendar',
  'event-collection-complete': 'event-collection-complete',
  'calendar-sunday-start': 'calendar-sunday-start',
  'calendar-hide-all-day-slot': 'calendar-hide-all-day-slot',
  'custom-events': 'custom-events',
  'schedule-rehab': 'schedule-rehab',
  'schedule-treatments': 'schedule-treatments',
  'calendar-web-drag-n-drop': 'calendar-web-drag-n-drop',
  'nested-checkbox-select': 'nested-checkbox-select',
  'date-picker-text-entry': 'date-picker-text-entry',
  'date-picker-short-format-display': 'date-picker-short-format-display',
  'mui-toasts': 'mui-toasts',
  'standard-date-formatting': 'standard-date-formatting',
  'naming-uploaded-files': 'naming-uploaded-files',
  'files-titles': 'files-titles',
  'drill-assignment-by-squad': 'drill-assignment-by-squad',
  'updated-error-screen': 'updated-error-screen',
  'repeat-events': 'repeat-events',
  'graph-pipeline-migration-summary': 'graph-pipeline-migration-summary',
  'event-attachments': 'event-attachments',
  'rpe-0-12-w-fractions': 'rpe-0-12-w-fractions',
  'rpe-0-12-w-fractions-game': 'rpe-0-12-w-fractions-game',
  'acute-chronic-inidividual': 'acute-chronic-inidividual',
  'single-page-application': 'single-page-application',
  'disable-mixpanel-tracking': 'disable-mixpanel-tracking',
  'tso-disable-upload-progress': 'tso-disable-upload-progress',
  'tso-video-analysis': 'tso-video-analysis',
  'benchmark-testing-area': 'benchmark-testing-area',
  'league-ops-mass-create-athlete-staff':
    'league-ops-mass-create-athlete-staff',
  'league-schedule-club-view': 'league-schedule-club-view',
  'tso-document-management': 'tso-document-management',
  'tso-forms-reviews': 'tso-forms-reviews',
  'tso-event-management': 'tso-event-management',
  'tso-league-fixture-management': 'tso-league-fixture-management',
  'tso-club-fixture-negotiation': 'tso-club-fixture-negotiation',
  'tso-league-jtc-fixture-management': 'tso-league-jtc-fixture-management',
  'tso-club-jtc-fixture-negotiation': 'tso-club-jtc-fixture-negotiation',
  'tso-fixture-finder': 'tso-fixture-finder',
  'tso-private-forms': 'tso-private-forms',
  'tso-recruitment': 'tso-recruitment',
  'league-ops-registration-module': 'league-ops-registration-module',
  'league-ops-registration-module-v2': 'league-ops-registration-module-v2',
  'league-ops-forms-qa': 'league-ops-forms-qa',
  'league-ops-squad-management': 'league-ops-squad-management',
  'conditional-fields-creation-in-ip': 'conditional-fields-creation-in-ip',
  'forms-generic-form-renderer': 'forms-generic-form-renderer',
  'view-form-templates-page': 'view-form-templates-page',
  'growth-and-maturation-area': 'growth-and-maturation-area',
  'performance-optimisation-imports': 'performance-optimisation-imports',
  'training-variables-importer': 'training-variables-importer',
  'benchmark-testing': 'benchmark-testing',
  'form-based-staff-profile': 'form-based-staff-profile',
  'league-ops-scouts-user-type': 'league-ops-scouts-user-type',
  'scout-schedule-view': 'scout-schedule-view',
  'league-ops-dmn-dmr-permissions': 'league-ops-dmn-dmr-permissions',
  'side-nav-update': 'side-nav-update',
  'date-picker-text-entry-athlete': 'date-picker-text-entry-athlete',
  'ip-login-branding': 'ip-login-branding',
  'assessments-grid-view': 'assessments-grid-view',
  'assessments-multiple-athletes': 'assessments-multiple-athletes',
  'game-ts-assessment-area': 'game-ts-assessment-area',
  'scales-colours': 'scales-colours',
  'rich-text-editor': 'rich-text-editor',
  'assessment-who-answered': 'assessment-who-answered',
  'league-ops-player-movement-medical-trial':
    'league-ops-player-movement-medical-trial',
  'league-ops-player-movement-trade': 'league-ops-player-movement-trade',
  'league-ops-player-movement-release': 'league-ops-player-movement-release',
  'planning-game-events-field-view': 'planning-game-events-field-view',
  'squad-numbers': 'squad-numbers',
  'rep-show-benchmark-reporting': 'rep-show-benchmark-reporting',
  'bm-testing-limit-season-and-age-filter':
    'bm-testing-limit-season-and-age-filter',
  'bm-testing-fe-side-performance-optimization':
    'bm-testing-fe-side-performance-optimization',
  'rep-show-growth-and-maturation-report':
    'rep-show-growth-and-maturation-report',
  'growth-and-maturation-pl-configuration':
    'growth-and-maturation-pl-configuration',
  'mirwald-calculation': 'mirwald-calculation',
  'g-and-m-new-columns': 'g-and-m-new-columns',
  'planning-session-planning': 'planning-session-planning',
  'planning-toggle-to-other-planning-views':
    'planning-toggle-to-other-planning-views',
  'athlete-profile-goals-and-reviews': 'athlete-profile-goals-and-reviews',
  'event-selector-side-nav': 'event-selector-side-nav',
  'player-selector-side-nav': 'player-selector-side-nav',
  'chat-web': 'chat-web',
  'admin-manage-fixtures-visibility': 'admin-manage-fixtures-visibility',
  'collections-side-panel': 'collections-side-panel',
  'game-details': 'game-details',
  'games-custom-duration-and-additional-time':
    'games-custom-duration-and-additional-time',
  'manually-add-opposition-name': 'manually-add-opposition-name',
  'event-locations': 'event-locations',
  'staff-visibility-custom-events': 'staff-visibility-custom-events',
  'planning-tab-sessions': 'planning-tab-sessions',
  'selection-tab-displaying-in-session': 'selection-tab-displaying-in-session',
  'duplicate-event-inside-an-event-nfl': 'duplicate-event-inside-an-event-nfl',
  'planning-custom-org-event-details': 'planning-custom-org-event-details',
  'mls-emr-advanced-options': 'mls-emr-advanced-options',
  'nfl-location-feed': 'nfl-location-feed',
  'nfl-hide-surface-type': 'nfl-hide-surface-type',
  'planning-show-event-title-in-creation-and-edit':
    'planning-show-event-title-in-creation-and-edit',
  'create-session-no-participants': 'create-session-no-participants',
  'planning-dual-write': 'planning-dual-write',
  'calendar-hide-gameday-field': 'calendar-hide-gameday-field',
  'nfl-2024-new-questions': 'nfl-2024-new-questions',
  'hide-format-and-fixture-rating': 'hide-format-and-fixture-rating',
  'squad-scoped-custom-events': 'squad-scoped-custom-events',
  'session-type-favourite': 'session-type-favourite',
  'session-theme': 'session-theme',
  'fixture-management-league-and-officials':
    'fixture-management-league-and-officials',
  'game-score-for-today-allowed': 'game-score-for-today-allowed',
  'surface-type-mandatory-sessions': 'surface-type-mandatory-sessions',
  'form-based-athlete-profile': 'form-based-athlete-profile',
  'league-ops-manage-athlete-league-level':
    'league-ops-manage-athlete-league-level',
  'manage-athletes-grid-mui': 'manage-athletes-grid-mui',
  'export-insurance-details': 'export-insurance-details',
  'bulk-activate-deactivate': 'bulk-activate-deactivate',
  'add-diagnostics-from-availability-sheet':
    'add-diagnostics-from-availability-sheet',
  'note-templates': 'note-templates',
  'league-ops-mass-create-pre-validate': 'league-ops-mass-create-pre-validate',
  'league-ops-mass-import': 'league-ops-mass-import',
  'league-ops-external-access-request': 'league-ops-external-access-request',
  'athlete-forms-list': 'athlete-forms-list',
  'repeat-reminders': 'repeat-reminders',
  'forms-scheduling': 'forms-scheduling',
  'update-manage-forms': 'update-manage-forms',
  'timezone-form-scheduling': 'timezone-form-scheduling',
  'tso-league-club-admin': 'tso-league-club-admin',
  'alerts-area': 'alerts-area',
  'staff-review-area': 'staff-review-area',
  'league-ops-officials-user-type': 'league-ops-officials-user-type',
  'coaching-library': 'coaching-library',
  'view-completed-forms-page': 'view-completed-forms-page',
  'export-page': 'export-page',
  'league-ops-officials-filter-post-api':
    'league-ops-officials-filter-post-api',
  'league-ops-governance-export': 'league-ops-governance-export',
  'league-ops-cards-export': 'league-ops-cards-export',
  'alerts-add-edit-delete': 'alerts-add-edit-delete',
  'duplicate-alerts': 'duplicate-alerts',
  'manage-forms-default-to-current-squad':
    'manage-forms-default-to-current-squad',
  'warning-answer': 'warning-answer',
  'league-ops-hide-squad-selector': 'league-ops-hide-squad-selector',
  'athlete-name-display-settings': 'athlete-name-display-settings',
  'integrations-tab-organisation-settings':
    'integrations-tab-organisation-settings',
  'organisation-settings-terminology-updates':
    'organisation-settings-terminology-updates',
  'custom-privacy-policy': 'custom-privacy-policy',
  'calendar-settings-ip': 'calendar-settings-ip',
  'location-settings-managements-on-i-p':
    'location-settings-managements-on-i-p',
  'hide-attachement-categories-settings-ip':
    'hide-attachement-categories-settings-ip',
  'league-ops-staff-league-export': 'league-ops-staff-league-export',
  'league-ops-update-registration-status':
    'league-ops-update-registration-status',
  'league-ops-payments-registration': 'league-ops-payments-registration',
  'league-ops-registration-v2-view-history':
    'league-ops-registration-v2-view-history',
  'league-ops-discipline-area': 'league-ops-discipline-area',
  'league-ops-schedule-menu': 'league-ops-schedule-menu',
  'league-ops-create-fixture-panel': 'league-ops-create-fixture-panel',
  'form-renderer-draft-mode': 'form-renderer-draft-mode',
  'nfl-session-participation-level-update':
    'nfl-session-participation-level-update',
  'planning-participation-reason': 'planning-participation-reason',
  'link-multi-injuries-to-participation-level':
    'link-multi-injuries-to-participation-level',
  'session-planning-download-sharing': 'session-planning-download-sharing',
  'league-ops-match-day-email-panel': 'league-ops-match-day-email-panel',
  'planning-game-events-tab-v-2': 'planning-game-events-tab-v-2',
  'delete-event-confirmation-modal': 'delete-event-confirmation-modal',
  'calendar-back-button-in-events': 'calendar-back-button-in-events',
  'planning-area-mui-data-grid': 'planning-area-mui-data-grid',
  'sessions-session-planning-tab': 'sessions-session-planning-tab',
  'selection-tab-games': 'selection-tab-games',
  'hide-update-drill-button': 'hide-update-drill-button',
  'group-by-athlete-selection-sessions': 'group-by-athlete-selection-sessions',
  'individual-game-rating': 'individual-game-rating',
  'show-position-view-ids': 'show-position-view-ids',
  'game-formations-editor': 'game-formations-editor',
  'set-overall-game-minutes': 'set-overall-game-minutes',
  'hide-game-events-header-and-events-list':
    'hide-game-events-header-and-events-list',
  'pitch-view-autosave': 'pitch-view-autosave',
  'league-ops-match-day-email-preview': 'league-ops-match-day-email-preview',
  'coaching-and-development-hide-participation-tab':
    'coaching-and-development-hide-participation-tab',
  'diagram-builder': 'diagram-builder',
  'planning-selection-tab': 'planning-selection-tab',
  'staff-selection-games': 'staff-selection-games',
  'league-ops-edit-players-button-fix': 'league-ops-edit-players-button-fix',
  'session-evaluation-coach': 'session-evaluation-coach',
  'web-calendar-athlete-filter': 'web-calendar-athlete-filter',
  'calendar-duplicate-event': 'calendar-duplicate-event',
  'scoped-squads-custom-events': 'scoped-squads-custom-events',
  'association-search-include-non-customers':
    'association-search-include-non-customers',
  'use-frontend-ff-sdk': 'use-frontend-ff-sdk',
  'sentry-route-tracker': 'sentry-route-tracker',
  'league-ops-expire-registration-profiles':
    'league-ops-expire-registration-profiles',
  'league-operations-edit-registration-profiles':
    'league-operations-edit-registration-profiles',
  'league-ops-discipline-area-v2': 'league-ops-discipline-area-v2',
  'league-ops-match-report-v2': 'league-ops-match-report-v2',
  'cp-messaging-notifications': 'cp-messaging-notifications',
  'league-ops-kit-management-v2': 'league-ops-kit-management-v2',
  'league-ops-match-monitor-v3': 'league-ops-match-monitor-v3',
};

export type FeatureFlagNames = $Values<typeof featureFlags>;

export default featureFlags;
