// @flow
// Documentation: https://kitmanlabs.atlassian.net/wiki/spaces/ENG/pages/352125059/WIP+Feature+Flag+Tracking+and+Management

const medicalFeatureFlags = {
  'acute-chronic-inidividual': 'acute-chronic-inidividual', // Status Form
  'allow-prior-club-recurrence': 'allow-prior-club-recurrence',
  'archive-diagnostic-redox': 'archive-diagnostic-redox',
  'archive-injury': 'archive-injury',
  'athlete-continuation-issues-endpoint':
    'athlete-continuation-issues-endpoint',
  'athlete-details-in-performance-medicine':
    'athlete-details-in-performance-medicine',
  'athlete-insurance-details': 'athlete-insurance-details',
  'athlete-run-medical-export': 'athlete-run-medical-export',
  'availability-info-disabled': 'availability-info-disabled',
  'c3logix-concussion': 'c3logix-concussion',
  'c3logix-concussion-iframe': 'c3logix-concussion-iframe',
  'cardiac-screening-v1': 'cardiac-screening-v1',
  'chronic-conditions-resolution': 'chronic-conditions-resolution',
  'chronic-conditions-updated-fields': 'chronic-conditions-updated-fields',
  'chronic-conditions-updates': 'chronic-conditions-updates',
  'chronic-injury-illness': 'chronic-injury-illness',
  'coaches-report-refactor': 'coaches-report-refactor',
  'coaches-report-v2': 'coaches-report-v2',
  'command-health-integration': 'command-health-integration',
  'concussion-entity-view': 'concussion-entity-view',
  'concussion-medical-area': 'concussion-medical-area',
  'concussion-web-iteration-2': 'concussion-web-iteration-2',
  'concussion-web-show-sac': 'concussion-web-show-sac',
  'concussion-web-team-tab': 'concussion-web-team-tab',
  'conditional-fields-creation-in-ip': 'conditional-fields-creation-in-ip',
  'conditional-fields-showing-in-ip': 'conditional-fields-showing-in-ip',
  'conditional-fields-v1-stop': 'conditional-fields-v1-stop',
  'confidential-notes': 'confidential-notes',
  'continuation-injury-player-movement': 'continuation-injury-player-movement',
  'covid-19-medical-diagnostic': 'covid-19-medical-diagnostic',
  'custom-pathologies': 'custom-pathologies',
  'diagnostics-billing-extra-fields': 'diagnostics-billing-extra-fields',
  'diagnostics-multiple-cpt': 'diagnostics-multiple-cpt',
  'diagnostics-tab-bulk-actions': 'diagnostics-tab-bulk-actions',
  'disable-parallel-injury-edits': 'disable-parallel-injury-edits',
  'disable-plc-if-outstanding-questions':
    'disable-plc-if-outstanding-questions',
  'display-plc-for-all-injuries': 'display-plc-for-all-injuries',
  'display-telephone-note': 'display-telephone-note',
  'dr-first-integration': 'dr-first-integration',
  'duplicate-treatment': 'duplicate-treatment',
  'edit-alerts-allergies': 'edit-alerts-allergies',
  'edit-diagnostic-redox': 'edit-diagnostic-redox',
  'editable-chronic-conditions': 'editable-chronic-conditions',
  'editable-injury-type': 'editable-injury-type',
  'emergency-contacts-report': 'emergency-contacts-report',
  'emergency-medical-report': 'emergency-medical-report',
  'emr-multiple-coding-systems': 'emr-multiple-coding-systems',
  'emr-orders': 'emr-orders',
  'emr-orders-reconciliation': 'emr-orders-reconciliation',
  'emr-show-latest-note-column': 'emr-show-latest-note-column',
  'examination-date': 'examination-date',
  'export-billing-buttons-team-level': 'export-billing-buttons-team-level',
  'export-multi-doc': 'export-multi-doc',
  'files-and-links-on-injuries': 'files-and-links-on-injuries',
  'fix-lazy-load-debounce': 'fix-lazy-load-debounce',
  'hide-player-left-club': 'hide-player-left-club',
  'inactive-athletes-tab-perf-med': 'inactive-athletes-tab-perf-med',
  'include-bamic-on-injury': 'include-bamic-on-injury',
  'incomplete-injury-fields': 'incomplete-injury-fields',
  'injured-filter-on-roster-page': 'injured-filter-on-roster-page',
  'injury-export-side-panel': 'injury-export-side-panel',
  'injury-game-period': 'injury-game-period',
  'injury-illness-name': 'injury-illness-name',
  'injury-onset-time-selector': 'injury-onset-time-selector',
  'injury-report-issue-type-field': 'injury-report-issue-type-field',
  'injury-surveillance-report': 'injury-surveillance-report',
  'issue-collapsable-reorder': 'issue-collapsable-reorder',
  'linked-injury-illness-performance-medicine':
    'linked-injury-illness-performance-medicine',
  'medical-additional-event-info-events':
    'medical-additional-event-info-events',
  'medical-alerts-side-panel': 'medical-alerts-side-panel',
  'medical-allow-update-injury-date': 'medical-allow-update-injury-date',
  'medical-bulk-export': 'medical-bulk-export',
  'medical-bulk-export-zip-options': 'medical-bulk-export-zip-options',
  'medical-closed-issue-plc-editing': 'medical-closed-issue-plc-editing',
  'medical-diagnostics-ambra': 'medical-diagnostics-ambra',
  'medical-diagnostics-iteration-3-billing-cpt':
    'medical-diagnostics-iteration-3-billing-cpt',
  'medical-documents-files-area': 'medical-documents-files-area',
  'medical-export-zip': 'medical-export-zip',
  'medical-fetch-shared-issues': 'medical-fetch-shared-issues',
  'medical-files-sort-by-doc-date': 'medical-files-sort-by-doc-date',
  'medical-files-tab-enhancement': 'medical-files-tab-enhancement',
  'medical-form-pdf-export-enabled': 'medical-form-pdf-export-enabled',
  'medical-forms-new-endpoints': 'medical-forms-new-endpoints',
  'medical-forms-tab-iteration-1': 'medical-forms-tab-iteration-1',
  'medical-global-add-button-fix': 'medical-global-add-button-fix',
  'medical-mass-scanning': 'medical-mass-scanning',
  'medical-mass-scanning-skip-validation':
    'medical-mass-scanning-skip-validation',
  'medical-medication-attachments': 'medical-medication-attachments',
  'medical-module-parent': 'medical-module-parent',
  'medical-mui-tabs': 'medical-mui-tabs',
  'medical-note-inherit-name': 'medical-note-inherit-name',
  'medical-procedure': 'medical-procedure',
  'medical-procedures': 'medical-procedures',
  'medical-roster-cache': 'medical-roster-cache',
  'medical-unlisted-meds': 'medical-unlisted-meds',
  'medications-general-availability': 'medications-general-availability',
  'medications-report': 'medications-report',
  'medications-report-export': 'medications-report-export',
  'mls-emr-action-due-date': 'mls-emr-action-due-date', // Annotations
  'mls-emr-advanced-options': 'mls-emr-advanced-options',
  'mls-emr-documents-area': 'mls-emr-documents-area',
  'mls-emr-psych-notes': 'mls-emr-psych-notes',
  'modifiable-player-left-club': 'modifiable-player-left-club',
  'multi-fave-select': 'multi-fave-select',
  'multi-part-injury-ci-code': 'multi-part-injury-ci-code',
  'nba-combined-ankle-export': 'nba-combined-ankle-export',
  'nba-show-demo': 'nba-show-demo',
  'nba-show-longitudinal-ankle-export': 'nba-show-longitudinal-ankle-export',
  'nfl-ancillary-data': 'nfl-ancillary-data',
  'nfl-coaches-report': 'nfl-coaches-report',
  'nfl-comments-tab': 'nfl-comments-tab',
  'nfl-disclaimer-popup-player-medical-record':
    'nfl-disclaimer-popup-player-medical-record',
  'nfl-efile': 'nfl-efile',
  'nfl-include-prior-club-issues': 'nfl-include-prior-club-issues',
  'nfl-injury-detail-report-export': 'nfl-injury-detail-report-export',
  'nfl-injury-flow-fields': 'nfl-injury-flow-fields',
  'nfl-injury-medication-report-export': 'nfl-injury-medication-report-export',
  'nfl-injury-report': 'nfl-injury-report',
  'nfl-player-movement-trade': 'nfl-player-movement-trade',
  'nfl-player-portal-web': 'nfl-player-portal-web', // Unsure who owns this
  'nfl-player-tryout': 'nfl-player-tryout',
  'note-author-field': 'note-author-field',
  'osha-form': 'osha-form',
  'past-athletes-medical-trial': 'past-athletes-medical-trial',
  'pdf-viewer-render-mode-canvas': 'pdf-viewer-render-mode-canvas', // Medical squad built this
  'performance-medicine-medical-history':
    'performance-medicine-medical-history',
  'player-movement-aware-datepicker': 'player-movement-aware-datepicker',
  'player-movement-entity-chronic-condition':
    'player-movement-entity-chronic-condition',
  'player-movement-entity-concussion-test':
    'player-movement-entity-concussion-test',
  'player-movement-entity-emr-annotations':
    'player-movement-entity-emr-annotations',
  'player-movement-entity-illness': 'player-movement-entity-illness',
  'player-movement-entity-injury': 'player-movement-entity-injury',
  'player-movement-entity-medical-documents':
    'player-movement-entity-medical-documents',
  'player-movement-entity-modifications':
    'player-movement-entity-modifications',
  'player-movement-entity-tue-vaccination':
    'player-movement-entity-tue-vaccination',
  'pm-efax-with-issue': 'pm-efax-with-issue',
  'pm-mls-emr-demo-froi': 'pm-mls-emr-demo-froi',
  'pm-mls-emr-demo-tue': 'pm-mls-emr-demo-tue',
  'pm-mass-scan-with-issue': 'pm-mass-scan-with-issue',
  'preliminary-injury-illness': 'preliminary-injury-illness',
  'print-diagnostics': 'print-diagnostics',
  'print-treatment-rehab-modals': 'print-treatment-rehab-modals',
  'quality-report-exports': 'quality-report-exports',
  'reason-for-reopening': 'reason-for-reopening',
  'pm-diagnostic-ga-enhancement': 'pm-diagnostic-ga-enhancement',
  redox: 'redox',
  'redox-iteration-1': 'redox-iteration-1',
  'referring-physician-treatments-diagnostics':
    'referring-physician-treatments-diagnostics',
  'rehab-delete-entire-session': 'rehab-delete-entire-session',
  'rehab-delete-exercise-confirmation': 'rehab-delete-exercise-confirmation',
  'rehab-groups': 'rehab-groups',
  'rehab-link-to-injury': 'rehab-link-to-injury',
  'rehab-maintenance-reason': 'rehab-maintenance-reason',
  'rehab-note': 'rehab-note',
  'rehab-post-injury-day-index': 'rehab-post-injury-day-index',
  'rehab-print-multi-player': 'rehab-print-multi-player',
  'rehab-print-single': 'rehab-print-single',
  'rehab-report-enhancements': 'rehab-report-enhancements',
  'rehab-search-mode-options': 'rehab-search-mode-options',
  'rehab-tab-athlete': 'rehab-tab-athlete',
  'rehab-tab-injury': 'rehab-tab-injury',
  'rehab-to-maintenance': 'rehab-to-maintenance',
  'rehab-tracker': 'rehab-tracker',
  'remove-attachments': 'remove-attachments',
  'replicate-treatments': 'replicate-treatments',
  'replicate-treatments-clear-actions': 'replicate-treatments-clear-actions',
  'roster-tab-v2': 'roster-tab-v2',
  'scanner-integration': 'scanner-integration',
  'show-isu-registration-forms-in-emr': 'show-isu-registration-forms-in-emr',
  'show-pl-forms-in-emr': 'show-pl-forms-in-emr',
  'stock-management': 'stock-management',
  'supplemental-recurrence-code': 'supplemental-recurrence-code',
  'tapered-meds': 'tapered-meds',
  'time-loss-activities-report-export': 'time-loss-activities-report-export',
  'time-loss-body-area-report': 'time-loss-body-area-report',
  'treatment-and-rehab-templates': 'treatment-and-rehab-templates',
  'treatment-on-view-issue': 'treatment-on-view-issue',
  'treatment-tracker-iteration-two': 'treatment-tracker-iteration-two',
  'treatments-billing': 'treatments-billing',
  'treatments-billing-extra-fields': 'treatments-billing-extra-fields',
  'treatments-location': 'treatments-location',
  'treatments-multi-modality': 'treatments-multi-modality',
  'update-perf-med-headers': 'update-perf-med-headers',
  'view-archive-injury-area': 'view-archive-injury-area',
  'workers-comp': 'workers-comp',
  'x-ray-game-day-report': 'x-ray-game-day-report',
  'pm-injury-edit-mode-of-onset': 'pm-injury-edit-mode-of-onset',
  'pm-default-injury-status-date': 'pm-default-injury-status-date',
  'pm-logic-builder-export-past-players':
    'pm-logic-builder-export-past-players',
  'pm-date-range-picker-custom': 'pm-date-range-picker-custom',
  'roster-player-injury-status-update': 'roster-player-injury-status-update',
  'availability-status-progress': 'availability-status-progress',
  'availability-status-polling': 'availability-status-polling',
};

export default medicalFeatureFlags;
