// @flow

export default {
  event: {
    venue_type: {
      id: 1,
      name: 'Home',
    },
    competition: {
      competition_categories: [],
      id: 1971,
      name: 'KLS',
      format: {
        id: 7,
        name: '11v11',
        number_of_players: 11,
      },
      min_substitutes: 1,
      max_substitutes: 9,
      min_staffs: 1,
      max_staffs: 9,
    },
    competition_category: null,
    opponent_squad: {
      id: 7535,
      name: '1st Team',
      owner_id: 1267,
      owner_name: 'KL Galaxy',
      logo_full_path: 'https://logo_full_path.com',
    },
    opponent_team: null,
    organisation_format: null,
    organisation_team: null,
    organisation_fixture_rating: null,
    opponent_score: 0,
    score: 0,
    squad: {
      id: 3496,
      name: 'U13',
      owner_id: 1268,
      owner_name: 'KL Toronto',
      logo_full_path: 'https://logo_full_path.com',
    },
    status: 'awaiting_officials',
    rpe_collection_kiosk: true,
    rpe_collection_athlete: true,
    mass_input: false,
    round_number: 234,
    game_time: '2024-11-04T19:00:00Z',
    league_setup: true,
    background_color: '#b134c1',
    number_of_periods: 2,
    editable: false,
    fas_game_key: null,
    mls_game_key: null,
    game_event_id: 1329821,
    disciplinary_issue: null,
    roster_submitted_by_id: null,
    match_report_submitted_by_id: null,
    external_id: null,
    overwrite_subs_staffs_limit: null,
    game_participants_unlocked: null,
    tv_channel: {
      id: 2,
      name: 'ESPN',
    },
    id: 3855163,
    name: null,
    start_date: '2024-11-04T20:00:00Z',
    end_date: '2024-11-04T21:30:00Z',
    duration: 90,
    type: 'game_event',
    local_timezone: 'Europe/London',
    surface_type: null,
    surface_quality: null,
    weather: null,
    temperature: null,
    humidity: null,
    field_condition: null,
    notification_schedule: {
      id: 3248779,
      scheduled_time: '2024-11-04T16:40:00-05:00',
      created_at: '2024-11-04T07:56:54.000-05:00',
      updated_at: '2024-11-04T07:56:54.000-05:00',
    },
    created_at: '2024-11-04T12:56:54Z',
    updated_at: '2024-11-04T12:56:54Z',
    nfl_surface_type_id: null,
    nfl_location_id: null,
    nfl_location_feed: null,
    nfl_equipment_id: null,
    nfl_surface_composition: null,
    nfl_field_type: null,
    workload_units: {},
    description: null,
    event_collection_complete: null,
    athlete_events_count: 0,
    attachments: [],
    attached_links: [],
    event_location: null,
    event_users: [],
    athlete_ids: [],
    visibility_ids: [],
    recurrence: {
      rule: null,
      recurring_event_id: null,
      original_start_time: null,
      rrule_instances: null,
    },
    has_associated_issues: false,
    associated_injury_occurrences: null,
    associated_illness_occurrences: null,
    tv_channels: [{ id: 1, name: 'ESPN' }],
    tv_game_contacts: [
      {
        id: 12,
        name: 'Contact name',
        organisation_id: 2,
        organisation: {
          id: 5,
          name: 'Organisation name',
          logo_full_path: null,
        },
        game_contact_roles: [
          {
            id: 8,
            name: 'Contact role',
            gameday_role: 'required',
            gameday_role_kind: 'league_contact',
            gameday_role_order: 9,
          },
        ],
        phone_number: '07111111111',
        email: 'name@kitmanlabs.com',
        dmn: true,
        dmr: true,
        status: 'approved',
        tv_channel_id: 1,
      },
    ],
  },
};
