// @flow
const data = [
  {
    id: 14282228,
    athlete: {
      id: 80524,
      athlete_squads: [
        { id: 10, name: 'squad 1 athlete 1' },
        { id: 101, name: 'squad 2 athlete 1' },
      ],
      firstname: 'Daniel Athlete',
      lastname: 'Athlete',
      fullname: 'Daniel Athlete Athlete',
      shortname: 'Athlete',
      user_id: 143222,
      avatar_url:
        'https://kitman-staging.imgix.net/avatar.jpg?auto=enhance&crop=faces&fit=crop&h=100&ixlib=rails-4.2.0&w=100',
      position: {
        id: 72,
        name: 'Loose-head Prop',
        order: 1,
        abbreviation: null,
      },
      availability: 'unavailable',
    },
    participation_level: {
      id: 1,
      name: 'Full',
      canonical_participation_level: 'full',
      include_in_group_calculations: true,
      default: true,
    },
    event_activity_ids: [9, 10],
    participation_level_reason: null,
    include_in_group_calculations: true,
    duration: 60,
    rpe: null,
    related_issue: null,
  },
  {
    id: 14282227,
    athlete: {
      id: 78041,
      athlete_squads: [
        { id: 10, name: 'squad 1 athlete 2' },
        { id: 101, name: 'squad 2 athlete 2' },
      ],
      firstname: 'Test',
      lastname: 'Athlete',
      fullname: 'Test Athlete',
      shortname: 'Athlete',
      user_id: 140145,
      avatar_url:
        'https://kitman-staging.imgix.net/avatar.jpg?auto=enhance&crop=faces&fit=crop&h=100&ixlib=rails-4.2.0&w=100',
      position: {
        id: 72,
        name: 'Loose-head Prop 2',
        order: 1,
        abbreviation: null,
      },
      availability: 'unavailable',
    },
    participation_level: {
      id: 2,
      name: 'Modified',
      canonical_participation_level: 'none',
      include_in_group_calculations: true,
      default: true,
    },
    event_activity_ids: [],
    participation_level_reason: null,
    include_in_group_calculations: false,
    duration: 60,
    rpe: null,
    related_issue: null,
  },
  {
    id: 14282162,
    athlete: {
      id: 15642,
      athlete_squads: [
        { id: 10, name: 'squad 1 athlete 3' },
        { id: 101, name: 'squad 2 athlete 3' },
      ],
      firstname: 'hugo',
      lastname: 'beuzeboc',
      fullname: 'hugo beuzeboc',
      shortname: 'beuzeboc',
      user_id: 17409,
      avatar_url:
        'https://kitman-staging.imgix.net/avatar.jpg?auto=enhance&crop=faces&fit=crop&h=100&ixlib=rails-4.2.0&w=100',
      position: {
        id: 72,
        name: 'Loose-head Prop 3',
        order: 1,
        abbreviation: null,
      },
      availability: 'unavailable',
    },
    participation_level: {
      id: 2,
      name: 'Modified',
      canonical_participation_level: 'none',
      include_in_group_calculations: true,
      default: true,
    },
    event_activity_ids: [],
    participation_level_reason: {
      id: 1,
      name: 'Injury',
    },
    include_in_group_calculations: true,
    duration: 60,
    rpe: null,
    related_issue: {
      archive_reason: null,
      archived: false,
      archived_by: null,
      archived_date: null,
      closed: false,
      created_at: '2022-07-13T08:01:15+01:00',
      created_by: {
        firstname: 'Daniel',
        fullname: 'Daniel Burke',
        id: 25878,
        lastname: 'Burke',
      },
      events: [
        {
          event_date: '2022-07-13T08:01:15+01:00',
          id: 24421,
          injury_status_id: 2,
        },
      ],
      examination_date: null,
      full_pathology: 'Ankle Fracture (Left)',
      id: 1,
      issue_id: 1,
      issue_occurrence_title: null,
      issue_type: 'Illness',
      occurrence_date: '2022-07-01T00:00:00+01:00',
      organisation_id: 6,
      reported_date: null,
      resolved_date: null,
      training_session_id: null,
      injury_status: {
        cause_unavailability: true,
        description: 'Causing unavailability (time-loss)',
        restore_availability: false,
      },
    },
  },
  {
    id: 14282230,
    athlete: {
      id: 81233,
      athlete_squads: [
        { id: 10, name: 'squad 1 athlete 4' },
        { id: 101, name: 'squad 2 athlete 4' },
      ],
      firstname: 'Bhuvan',
      lastname: 'Bhatt',
      fullname: 'Bhuvan Bhatt',
      shortname: 'Bhatt',
      user_id: 144027,
      avatar_url:
        'https://kitman-staging.imgix.net/avatar.jpg?auto=enhance&crop=faces&fit=crop&h=100&ixlib=rails-4.2.0&w=100',
      position: {
        id: 72,
        name: 'Loose-head Prop 4',
        order: 1,
        abbreviation: null,
      },
      availability: 'unavailable',
    },
    participation_level: {
      id: 1,
      name: 'Full',
      canonical_participation_level: 'full',
      include_in_group_calculations: true,
      default: true,
    },
    event_activity_ids: [],
    participation_level_reason: null,
    include_in_group_calculations: true,
    duration: 60,
    rpe: null,
    related_issue: null,
  },
];

export default data;
