// @flow
export type SettingsPermissions = {
  canViewSettingsAthletes: boolean,
  canManageStaffUsers: boolean,
  canViewSettingsQuestionnaire: boolean,
  canViewOrganisationSettings: boolean,
  canManagePrivacySettings: boolean,
  canViewSettingsEmergencyContacts: boolean,
  canViewSettingsInsurancePolicies: boolean,
  canViewPlanningAdmin: boolean,
  canViewImports: boolean,
  canCreateImports: boolean,
  canManageOfficials: boolean,
  canRunLeagueExports: boolean,
  canViewExportsArea: boolean,
  canManageScouts: boolean,
  canManageMatchDirectors: boolean,
  canManageMatchMonitors: boolean,
  canViewLabels: boolean,
  canAssignLabels: boolean,
  isLabelsAdmin: boolean,
  isSegmentsAdmin: boolean,
  canViewSegments: boolean,
  canViewStaffUsers: boolean,
};
