// @flow

export default [
  {
    id: 84,
    sport_id: 1,
    position_group_id: 28,
    name: 'Goalkeeper',
    abbreviation: 'GK',
    order: 1,
  },
  {
    id: 85,
    sport_id: 1,
    position_group_id: 29,
    name: 'Sweeper',
    abbreviation: 'SWP',
    order: 7,
  },
  {
    id: 86,
    sport_id: 1,
    position_group_id: 29,
    name: 'Centre Back',
    abbreviation: 'CB',
    order: 4,
  },
  {
    id: 87,
    sport_id: 1,
    position_group_id: 29,
    name: 'Right Back',
    abbreviation: 'RB',
    order: 2,
  },
  {
    id: 88,
    sport_id: 1,
    position_group_id: 29,
    name: 'Left Back',
    abbreviation: 'LB',
    order: 5,
  },
  {
    id: 89,
    sport_id: 1,
    position_group_id: 29,
    name: 'Left Wing Back',
    abbreviation: 'LWB',
    order: 6,
  },
  {
    id: 90,
    sport_id: 1,
    position_group_id: 29,
    name: 'Right Wing Back',
    abbreviation: 'RWB',
    order: 3,
  },
  {
    id: 91,
    sport_id: 1,
    position_group_id: 30,
    name: 'Defensive Midfielder',
    abbreviation: 'DM',
    order: 8,
  },
  {
    id: 92,
    sport_id: 1,
    position_group_id: 30,
    name: 'Central Midfielder',
    abbreviation: 'CM',
    order: 10,
  },
  {
    id: 93,
    sport_id: 1,
    position_group_id: 30,
    name: 'Attacking Midfielder',
    abbreviation: 'AM',
    order: 12,
  },
  {
    id: 94,
    sport_id: 1,
    position_group_id: 30,
    name: 'Left Wing',
    abbreviation: 'LW',
    order: 11,
  },
  {
    id: 95,
    sport_id: 1,
    position_group_id: 30,
    name: 'Right Wing',
    abbreviation: 'RW',
    order: 9,
  },
  {
    id: 96,
    sport_id: 1,
    position_group_id: 31,
    name: 'Centre Forward',
    abbreviation: 'CF',
    order: 14,
  },
  {
    id: 97,
    sport_id: 1,
    position_group_id: 31,
    name: 'Wing Forward',
    abbreviation: 'WF',
    order: 13,
  },
  {
    id: 98,
    sport_id: 1,
    position_group_id: 32,
    name: 'Other',
    abbreviation: 'Oth',
    order: 15,
  },
  {
    id: 721,
    sport_id: 1,
    position_group_id: 31,
    name: 'Striker',
    abbreviation: 'ST',
    order: 16,
  },
  {
    id: 722,
    sport_id: 1,
    position_group_id: 30,
    name: 'Left Midfielder',
    abbreviation: 'LM',
    order: 12,
  },
  {
    id: 723,
    sport_id: 1,
    position_group_id: 30,
    name: 'Right Midfielder',
    abbreviation: 'RM',
    order: 12,
  },
];
