// @flow
export const TAGS = {
  ORGANISATIONS: 'ORGANISATIONS',
  ORGANISATION: 'ORGANISATION',
  SQUADS: 'SQUADS',
  USERS: 'USERS',
  STAFF: 'STAFF',
  ATHLETES: 'ATHLETES',
  REGISTRATION_PROFILE: 'REGISTRATION_PROFILE',
  REGISTRATION_SQUAD_HISTORY: 'REGISTRATION_SQUAD_HISTORY',
  REGISTRATION_PROFILE_FORM: 'REGISTRATION_PROFILE_FORM',
  REGISTRATION_FORM: 'REGISTRATION_FORM',
  REGISTRATION_REQUIREMENTS_PROFILE_FORM:
    'REGISTRATION_REQUIREMENTS_PROFILE_FORM',
  REGISTRATION_GRID: 'REGISTRATION_GRID',
  REQUIREMENT_SECTION: 'REQUIREMENT_SECTION',
  REQUIREMENTS: 'REQUIREMENTS',
  REGISTRATION_ORGANISATION: 'REGISTRATION_ORGANISATION',
  CLUB_PAYMENT: 'CLUB_PAYMENT',
  REGISTRATION_SQUAD: 'REGISTRATION_SQUAD',
  REGISTRATION_HISTORY: 'REGISTRATION_HISTORY',
  DISCIPLINES: 'DISCIPLINES',
  REGISTRATION_STATUS: 'REGISTRATION_STATUS',
  REGISTRATION_STATUS_FILTERS: 'REGISTRATION_STATUS_FILTERS',
  SECTION_STATUSES: 'SECTION_STATUSES',
  HOMEGROWN_ASSOCIATION_TOTALS: 'HOMEGROWN_ASSOCIATION_TOTALS',
  HOMEGROWN_ORGANISATION_TOTALS: 'HOMEGROWN_ORGANISATION_TOTALS',
  HOMEGROWN: 'HOMEGROWN',
};

// TODO: add full type support here
// paginatedMergeStrategy<T> = (currentCache: T, newItems: T)
export const paginatedMergeStrategy = (currentCache: any, newItems: any) => {
  // eslint-disable-next-line no-param-reassign
  currentCache.meta = newItems.meta;
  if (newItems?.meta?.current_page === 1) {
    // eslint-disable-next-line no-param-reassign
    currentCache.data = newItems.data;
  } else currentCache.data.push(...newItems.data);
};
