// @flow
import i18n from '@kitman/common/src/utils/i18n';

export const nflPlayerDisclaimer1Content = () => (
  <>
    <p>
      {i18n.t(`This EMR Player Portal (“Portal”) has been developed by Kitman Labs and is offered to this NFL
      player (“the Player”) for purposes of accessing and reviewing personal medical information in
      the EMR system, Kitman Labs Intelligence Platform (iP). Through this User
      Agreement, the NFL and its member Clubs grant the Player permission to use the Portal
      pursuant to the terms and conditions contained in this User Agreement and in strict compliance
      with these terms and conditions and with all applicable laws.`)}
    </p>
    <p>
      {i18n.t(
        `In connection with his use of the Portal, the Player agrees to the following terms and conditions:`
      )}
    </p>
    <p>
      <strong>{i18n.t('Username and Password.')}</strong>{' '}
      {i18n.t(`The Player is granted access to the Portal through a unique and
      individualized username with password that is auto-generated by the EMR system, 
      Kitman Labs Intelligence Platform (iP). Upon first logging on to the Portal, the Player will
      create a new, customized password. The Player shall protect and keep his username and
      password secure and confidential at all times; and shall not share his username or password
      with any other person or entity, or allow any person or entity to use his username or password
      to access the Portal. The Player is solely responsible for protecting the confidentiality of his
      username and password.`)}
    </p>
    <p>
      <strong>{i18n.t(`Use & Disclosure.`)}</strong>{' '}
      {i18n.t(`The Player agrees to use the Portal in accordance with all applicable laws
      and with all rules, terms, procedures, and conditions established by the NFL and its member
      Clubs governing the use of the Portal. The Player also understands that activities on the Portal
      may be monitored to ensure compliance with these terms and conditions. The Player is solely
      responsible for all activity and uses which occur on the Portal under his username and
      password. The Player will be solely responsible for any and all improper uses and/or disclosures
      of the Portal that occur through the use of his username or password. The player will not
      access, use, or disclose any confidential information contained on the Portal other than his own
      information. The Player agrees that neither the NFL nor its member Clubs will be responsible or
      liable in any way for any uses and/or disclosures that occur through the use of the Player's
      username or password, whether those uses and/or disclosures are improper or not.`)}
    </p>
    <p>
      <strong>{i18n.t(`Confidentiality.`)}</strong>{' '}
      {i18n.t(`The Player acknowledges and agrees that he is solely responsible for
      maintaining and protecting the confidentiality of any personal or confidential information that is
      downloaded, printed, saved, removed from, or otherwise extracted from the Portal under his
      username and password. The Player is aware and understands that if he shares, discloses,
      broadcasts, publishes, publicizes, communicates, or disseminates—whether directly or
      indirectly, intentionally or unintentionally—any personal or confidential information contained on
      the Portal with a third party, including but not limited to, an agent, the press/media, a non-Club
      affiliated doctor or medical entity, then the Player is solely responsible for that disclosure. The
      Player acknowledges and understands that if he shares or discloses his personal information to
      others, then that information may no longer be protected by federal or state privacy laws or
      regulations.`)}
    </p>
    <p>
      <strong>
        {i18n.t(`Notice of Breach or Improper Use or Disclosure.`)}
      </strong>{' '}
      {i18n.t(`The Player shall notify his Club's Privacy
      Officer immediately of the following, and this notice must be given in person, by phone, or in
      writing:`)}
    </p>
    <ol type="a">
      <li>
        {i18n.t(`Any breach of confidentiality which the Player knows of, or in the exercise of
          reasonable diligence, should have known of;`)}
      </li>
      <li>
        {i18n.t(`Any use or disclosure of any Player's confidential information that is not
          permitted under this User Agreement or applicable state or federal law;`)}
      </li>
      <li>
        {i18n.t(`Any viruses, malware, or any kind of harmful computer programs that have been
          introduced into the Portal;`)}
      </li>
      <li>
        {i18n.t(`Any suspicion that another individual or entity has access to the Player's
          username, password, or account or has improperly used his/her username,
          password, or account; and/or`)}
      </li>
      <li>{i18n.t(`Any lost or stolen username or password.`)}</li>
    </ol>
    <p>
      <strong>{i18n.t(`Safeguards.`)}</strong>{' '}
      {i18n.t(`The Player shall maintain all appropriate safeguards for all devices, software, and
      hardware he uses to access the Portal, and these safeguards must reasonably protect the
      integrity, privacy, and security of the Portal as required by applicable state and federal law. The
      Player will take all appropriate steps to protect the Portal from viruses, malware, or any kind of
      harmful computer program.`)}
    </p>
    <p>
      <strong>{i18n.t(`Security.`)}</strong>{' '}
      {i18n.t(`The Player must also have adequate security with respect to any devices or
      equipment that the Player uses to access the Portal. The security measures must satisfy all
      applicable state and federal law. The Player shall immediately notify the Privacy Officer of the
      appropriate Club(s) of any security incident of which the Player becomes aware. This notice
      must be given in person, by phone, or in writing. The Player will also implement and maintain
      adequate safeguards for the transport and disposal of any devices or equipment in the Player's
      possession, custody, or control which may contain, maintain, or store the Players' confidential
      medical information.`)}
    </p>
    <p>
      <strong>{i18n.t(`Mitigation and Cooperation.`)}</strong>{' '}
      {i18n.t(`The Player shall mitigate any harmful effects known to him
      arising out of the Player's use of the Portal. The Player shall cooperate fully with his Club, and
      with any other person or entity the Club utilizes, in its efforts to investigate, mitigate, and remedy
      any breach and/or any unauthorized use or disclosure in connection with the Portal, including
      any suspected breach and/or any suspected unauthorized use or disclosure in connection with
      the Portal.`)}
    </p>
    <p>
      <strong>{i18n.t(`Deactivation of Player's Access.`)}</strong>{' '}
      {i18n.t(`The Player's Club reserves the right to deactivate at any
      time, with immediate effect and without notice to the Player, the Player's access to the Portal if
      the Player's Club determines, or it is brought to the Club's attention, that the Player is not
      utilizing the Portal in compliance with this User Agreement and/or state or federal law, or for any
      other reason or no reason. If the Player is subject to disciplinary action and his access to the
      Portal is ultimately suspended or deactivated due to that misuse, the Player may receive his
      medical records by alternate means instead of the Portal in accordance with the 2020 Collective
      Bargaining Agreement.`)}
    </p>
    <p>
      <strong>{i18n.t(`Limitations of Liability.`)}</strong>{' '}
      {i18n.t(`The Player acknowledges that there are risks inherent in accessing
      and using electronic medical information contained on the Portal, including typographical errors,
      timeliness, accuracy, and medical images that may be of a different resolution and quality from
      those stored on other media. The Player therefore assumes all risks arising out of or associated
      with his use of the Portal. The Player acknowledges and agrees that: (a) neither the NFL nor
      any of its member Clubs will be responsible or liable for any direct, indirect, incidental,
      consequential, special, punitive, or any other damages arising out of the Player's electronic use
      of, or inability to use, the Portal; and (b) neither the NFL nor any of its member Clubs will be
      responsible or liable for any alleged damages or losses incurred by the Player or any other
      individual or entity arising out of the Player's use of, or inability to use, the Portal. In the event
      of any problem with the Portal or any of its content, the Player agrees that neither the NFL nor
      any of its member Clubs will be responsible or liable in any way for the Player's reliance upon or
      use of the Portal or any of its content, including but not limited to, any errors or omissions in any
      content, or any loss or damage of any kind incurred as a result of the use of or reliance upon
      any content contained on the Portal.`)}
    </p>
    <p>
      <strong>{i18n.t(`Indemnification.`)}</strong>{' '}
      {i18n.t(`The Player agrees to fully defend, indemnify, and hold harmless the NFL
      and/or its member Clubs against any and all claims, actions, complaints, causes of action, suits,
      debts, litigation, damages, fines, levies, assessments, consent agreements, settlements,
      government actions, administrative proceedings, and any other liabilities, in law or in equity,
      arising out of: (a) the Player's improper use of the Portal; (b) the Player's violation of any
      provision of this User Agreement; and/or (c) the Player's improper use or disclosure of his
      confidential medical information. The Player's indemnity obligation is triggered even if his
      improper use of the Portal or improper use or disclosure of his information was caused in part
      by an action or omission of the NFL and/or the Club.`)}
    </p>
    <p>
      <strong>{i18n.t(`Release.`)}</strong>{' '}
      {i18n.t(`The Player expressly, knowingly, and voluntarily releases and holds harmless the
      NFL and its member Clubs from any and all legal liability, claims, actions, complaints, causes of
      action, suits, debts, litigation, damages, fines, assessments, consent agreements, settlements,
      government actions, administrative proceedings, and any other liabilities, in law or in equity,
      arising out of the Player's use of the Portal.`)}
    </p>
    <p>
      <strong>{i18n.t(`No Medical Advice.`)}</strong>{' '}
      {i18n.t(`The Portal is intended to be an informational tool for the Player to be used
      as a convenience for the Player. The Portal is not a means of providing the Player with medical
      advice, counseling, evaluation, or instruction. The Portal should never be used as a substitute
      for direct communication with or advice from a qualified healthcare provider. If the Player has
      healthcare needs, questions, or concerns, the Player should seek assistance and/or advice from
      a qualified healthcare provider and should not rely upon the Portal.`)}
    </p>
    <p>
      <strong>{i18n.t(`No Warranties.`)}</strong>{' '}
      {i18n.t(`The Portal and its content are provided to the Player on an "as is" basis.
      Neither the NFL nor its member Clubs makes any representations or warranties regarding the
      use of the Portal or its contents, whether or not that content has been provided by the Clubs or
      by third parties. To the fullest extent provided by law, the NFL and its member Clubs expressly
      disclaim any warranties, whether express or implied, relating to the Portal. Further, neither the
      NFL nor its member Clubs make any representations or warranties regarding the reliability,
      accuracy, correctness, completeness, integrity, and/or timeliness of the information contained
      on the Portal. Neither the NFL nor its member Clubs represent, warranty, or guarantee that the
      Portal will function continuously, without error, or without interruption.`)}
    </p>
    <p>
      <strong>{i18n.t(`Changes and Modifications.`)}</strong>{' '}
      {i18n.t(`The NFL and/or its member Clubs may make changes or modifications to the terms, conditions, 
      and rules governing the use of the Portal. If changes are made, the Player will be given notice through 
      a pop-up screen that will display the terms and conditions, and the Player will be required to agree to the 
      terms and conditions by clicking upon an icon where indicated.`)}
    </p>
    <p>
      <strong>{i18n.t(`Proprietary Information.`)}</strong>{' '}
      {i18n.t(`The Portal may contain proprietary information and material that is
      protected by federal, state, and/or international law relating to intellectual property and/or trade
      secret information, including but not limited to, copyright law, trademark law, and patent law.
      This User Agreement does not grant to the Player any rights to such information. The Player's
      access to the Portal is limited to his own personal medical information. Except as expressly set
      forth in this User Agreement, the Player may not download, copy, publish, disseminate, or
      reproduce any other content contained on the Portal without the written permission of the NFL
      or the Player's Club.`)}
    </p>
    <p>
      <strong>{i18n.t(`Enforcement.`)}</strong>{' '}
      {i18n.t(`The Club has the right to enforce any and all terms of this User Agreement
      through litigation commenced by the Club against the Player, seeking damages and/or
      injunctive relief under any theory of law or equity. The Player may also be subject to disciplinary
      action for a violation of any of the rules, terms, and/or conditions governing the use of the Portal,
      including the violation of any provision of this User Agreement. The Club's failure to exercise, or
      delay in exercising, any right, remedy, power or privilege arising out of this User Agreement
      shall not operate as a waiver thereof; nor shall any single or partial exercise of any right,
      remedy, power or privilege arising out of this User Agreement preclude any other or further
      exercise thereof or the exercise of any other right, remedy, power or privilege.`)}
    </p>
    <p>
      <strong>{i18n.t(`Termination.`)}</strong>{' '}
      {i18n.t(`The Club may terminate this User Agreement at any time and for any reason or
      no reason without prior notice to the Player. The Player's obligations with respect to use and
      disclosure, confidentiality, notice, cooperation, mitigation, and indemnity under this User
      Agreement survive the termination of the User Agreement for any reason or no reason.`)}
    </p>
    <p>
      <strong>{i18n.t(`Governing Law.`)}</strong>{' '}
      {i18n.t(`The Player and the Club agree that this User Agreement is deemed to be
      made in New York, and it shall be governed and construed according to the laws of New York in
      all respects, including matters of construction, interpretation, enforcement, and validity, without
      regard to conflict of law / choice of law rules or provisions. The Player agrees and consents to
      exclusive personal and subject matter jurisdiction and venue in the state and federal courts of
      New York for the adjudication of any and all disputes between the parties concerning this
      Agreement.`)}
    </p>
    <p>
      <strong>{i18n.t(`Severability.`)}</strong>{' '}
      {i18n.t(`In the event that any portion of part(s) of this User Agreement should be found to
      be void or held by any court of competent jurisdiction to be invalid or unenforceable for any
      reason, the remainder of this User Agreement shall remain in full force and effect.`)}
    </p>
    <p>
      <strong>
        {i18n.t(`BY SELECTING “I AGREE” IN THE ICON BELOW, THE PLAYER CERTIFIES THAT HE
        HAS READ THIS USER AGREEMENT, UNDERSTANDS ITS CONTENTS, AND AGREES TO
        COMPLY AND ABIDE BY ITS TERMS AND CONDITIONS.`)}
      </strong>
    </p>
  </>
);

export const nflPlayerDisclaimer2Content = () => (
  <p>
    <strong>{i18n.t(`Acknowledgement of Risks and Limitations.`)}</strong>{' '}
    {i18n.t(`The User acknowledges that there are risks
    inherent in accessing and using electronic medical information contained on this NFL Player
    Portal (“Portal”), including typographical errors, timeliness, accuracy, and medical images that
    may be of a different resolution and quality from those stored in other media. The User therefore
    assumes all risks arising out of or associated with his use of the Portal. The User acknowledges
    that the health records and data accessed via the Portal's Export function may not reflect the most
    up-to-date records or data in the EMR system, Kitman Labs Intelligence Platform (iP).
    Specifically, the User acknowledges that medical records or data created or added to the EMR
    System within seven (7) days prior to the time of Export will not be included in the User records
    accessed via the Portal's Export function. The User acknowledges and agrees that: (a) neither
    the NFL nor any of its member Clubs will be responsible or liable for any direct, indirect, incidental,
    consequential, special, punitive, or any other damages of any kind arising out of the User's
    electronic use of, or inability to use, the Portal; and (b) neither the NFL nor any of its member
    Clubs will be responsible or liable for any alleged damages or losses incurred by the User or any
    other individual or entity arising out of the User's use of, or inability to use, the Portal. In the event
    of any problem with the Portal or any of its content, the User agrees that neither the NFL nor any
    of its member Clubs will be responsible or liable in any way for the User's reliance upon or use of
    the Portal or any of its content, including but not limited to, any errors or omissions in any content,
    or any loss or damage of any kind incurred as a result of the use of or reliance upon any content
    contained on the Portal.`)}
  </p>
);
