// @flow
export default {
  element_type: 'Forms::Elements::Layouts::Menu',
  index: 0,
  items: [
    {
      element_type: 'Forms::Elements::Layouts::MenuGroup',
      index: 0,
      items: [
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 0,
          key: 'playerdetails',
          title: 'Player Details',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 1,
          key: 'parentguardian',
          title: 'Parents/ Guardian',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 2,
          key: 'insurance',
          title: 'Insurance',
          items: [],
        },
      ],
      key: 'personal_details',
      title: 'Personal Details',
    },
    {
      element_type: 'Forms::Elements::Layouts::MenuGroup',
      index: 1,
      items: [
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 0,
          key: 'attachment_section_headshot',
          title: 'Headshot',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 1,
          key: 'attachment_section_proof_of_birth',
          title: 'Proof of Birth',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 2,
          key: 'attachment_section_impact_baseline',
          title: 'ImPACT Baseline Test',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 3,
          key: 'attachment_section_itc',
          title: 'International Transfer Certificate',
          items: [],
        },
      ],
      key: 'attachments',
      title: 'Documents',
    },
    {
      element_type: 'Forms::Elements::Layouts::MenuGroup',
      index: 2,
      items: [
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 0,
          key: 'acknowledgement_privacy_policy_section',
          title: 'Privacy Policy',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 1,
          key: 'acknowledgement_health_information_release_section',
          title: 'Player Authorization for the Release of Health Information',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 2,
          key: 'acknowledgement_rules_regulations_section',
          title: 'Rules and Regulations',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 3,
          key: 'acknowledgement_participant_waiver_section',
          title: 'Participant Agreement and Waiver',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 4,
          key: 'acknowledgement_code_conduct_section',
          title: 'Code of Conduct',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 5,
          key: 'acknowledgement_mls_next_section',
          title: 'MLS NEXT Acknowledgements',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 6,
          key: 'acknowledgement_diversity_section',
          title: 'Diversity, Equity and Inclusion',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 7,
          key: 'acknowledgement_housing_section',
          title: '23/24 Housing Information',
          items: [],
        },
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 8,
          key: 'signatures',
          title: 'Signature',
          items: [],
        },
      ],
      key: 'policies',
      title: 'Policies & Signatures',
    },
    {
      element_type: 'Forms::Elements::Layouts::MenuGroup',
      index: 3,
      items: [
        {
          element_type: 'Forms::Elements::Layouts::MenuItem',
          index: 0,
          key: 'attachment_safesport_section',
          title: 'SafeSport',
          items: [],
        },
      ],
      key: 'courses',
      title: 'Courses',
    },
  ],
  key: 'menu',
  title: 'MLS Next 23/24',
};
