// @flow
export const dmrData = {
  logo_url: 'champions_league_logo.png',
  match_details: {
    match_no: '1234',
    date: 'Wednesday, May 26, 1999',
    time: '7:45 PM',
    kick_time: '7:45 PM',
    venue: 'Camp Nou',
    tv: 'RTE',
    referee: 'Pierluigi Collina',
    var: null,
    avar: null,
    assistant_referee_1: 'Gennaro Mazzei',
    assistant_referee_2: 'Claudio Puglisi',
    fourth_referee: 'Fiorenzo Treossi',
    reserve_ar: 'John Doe',
    timestamp: '1999-05-26 12:00:00 GMT',
  },
  home: {
    logo_url: 'man_utd_badge.png',
    name: 'Manchester United',
    formation: '4-4-2',

    starters: [
      {
        name: 'Peter Schmeichel',
        position: 'Goalkeeper',
        position_order: 1,
        jersey_number: 1,
        captain: true,
        avatar: 'avatar.png',
      },
      {
        name: 'Gary Neville',
        position: 'Defender',
        position_order: 2,
        jersey_number: 2,
        captain: false,
        avatar: 'avatar.png',
      },
      {
        name: 'Ronny Johnsen',
        position: 'Defender',
        position_order: 3,
        jersey_number: 5,
        captain: false,
        avatar: 'avatar.png',
      },
      {
        name: 'Jaap Stam',
        position: 'Defender',
        position_order: 4,
        jersey_number: 6,
        captain: false,
        avatar: 'avatar.png',
      },
      {
        name: 'Denis Irwin',
        position: 'Defender',
        position_order: 5,
        jersey_number: 3,
        captain: false,
        avatar: 'avatar.png',
      },
      {
        name: 'Ryan Giggs',
        position: 'Midfielder',
        position_order: 6,
        jersey_number: 11,
        captain: false,
        avatar: 'avatar.png',
      },
      {
        name: 'David Beckham',
        position: 'Midfielder',
        position_order: 7,
        jersey_number: 7,
        captain: false,
        avatar: 'avatar.png',
      },
      {
        name: 'Nicky Butt',
        position: 'Midfielder',
        position_order: 8,
        jersey_number: 8,
        captain: false,
        avatar: 'avatar.png',
      },
      {
        name: 'Jesper Blomqvist',
        position: 'Midfielder',
        position_order: 9,
        jersey_number: 15,
        captain: false,
      },
      {
        name: 'Dwight Yorke',
        position: 'Attacker',
        position_order: 10,
        jersey_number: 19,
        captain: false,
        avatar: 'avatar.png',
      },
      {
        name: 'Andy Cole',
        position: 'Attacker',
        position_order: 11,
        jersey_number: 9,
        captain: false,
      },
    ],
    substitutes: [
      {
        name: 'Teddy Sheringham',
        position: 'Attacker',
        position_order: null,
        jersey_number: 10,
        captain: false,
      },
      {
        name: 'Ole Gunnar Solskjaer',
        position: 'Attacker',
        position_order: 1,
        jersey_number: 12,
        captain: false,
        avatar: 'avatar.png',
      },
    ],
    bench_personnel: [
      {
        name: 'Alex Ferguson',
        role: 'Manager',
      },
      {
        name: 'Steve McClaren',
        role: 'Assistant Coach',
      },
    ],
  },
  away: {
    logo_url: 'bayern_badge.png',
    name: 'Bayern Munich',
    formation: '5-2-3',
    starters: [
      {
        name: 'Oliver Kahn',
        position: 'Goalkeeper',
        position_order: 1,
        jersey_number: 1,
        captain: true,
        avatar: 'avatar.png',
        date_of_birth: '1969-09-21',
        kitman_id: '1234567890',
      },
      {
        name: 'Lothar Matthäus',
        position: 'Defender',
        position_order: 2,
        jersey_number: 10,
        captain: false,
        avatar: 'avatar.png',
        date_of_birth: '1969-09-21',
        kitman_id: '1234567890',
      },
      {
        name: 'Markus Babbel',
        position: 'Defender',
        position_order: 3,
        jersey_number: 2,
        captain: false,
        avatar: 'avatar.png',
        date_of_birth: '1969-09-21',
        kitman_id: '1234567890',
      },
      {
        name: 'Thomas Linke',
        position: 'Defender',
        position_order: 4,
        jersey_number: 25,
        captain: false,
        avatar: 'avatar.png',
        date_of_birth: '1969-09-21',
        kitman_id: '1234567890',
      },
      {
        name: 'Samuel Kuffour',
        position: 'Defender',
        position_order: 5,
        jersey_number: 4,
        captain: false,
        avatar: 'avatar.png',
        date_of_birth: '1969-09-21',
        kitman_id: '1234567890',
      },
      {
        name: 'Michael Tarnat',
        position: 'Defender',
        position_order: 6,
        jersey_number: 18,
        captain: false,
        avatar: 'avatar.png',
        date_of_birth: '1969-09-21',
        kitman_id: '1234567890',
      },
      {
        name: 'Stefan Effenberg',
        position: 'Midfielder',
        position_order: 7,
        jersey_number: 11,
        captain: false,
        avatar: 'avatar.png',
        date_of_birth: '1969-09-21',
        kitman_id: '1234567890',
      },
      {
        name: 'Jens Jeremies',
        position: 'Midfielder',
        position_order: 8,
        jersey_number: 16,
        captain: false,
        avatar: 'avatar.png',
      },
      {
        name: 'Mario Basler',
        position: 'Attacker',
        position_order: 9,
        jersey_number: 14,
        captain: false,
        date_of_birth: '1969-09-21',
        kitman_id: '1234567890',
      },
      {
        name: 'Carsten Jancker',
        position: 'Attacker',
        position_order: 10,
        jersey_number: 19,
        captain: false,
        avatar: 'avatar.png',
      },
      {
        name: 'Alexander Zickler',
        position: 'Attacker',
        position_order: 11,
        jersey_number: 21,
        captain: false,
      },
    ],
    substitutes: [
      {
        name: 'Mehmet Scholl',
        position: 'Attacker',
        position_order: null,
        jersey_number: 7,
        captain: false,
      },
      {
        name: 'Thorsten Fink',
        position: 'Attacker',
        position_order: 1,
        jersey_number: 17,
        captain: false,
        avatar: 'avatar.png',
      },
    ],
    bench_personnel: [
      {
        name: 'Ottmar Hitzfeld',
        role: 'Manager',
      },
      {
        name: 'Michael Henke',
        role: 'Assistant Coach',
      },
    ],
  },
};
export const dmnData = {
  logo_url: 'champions_league_logo.png',
  match_details: {
    match_no: '1234',
    date: 'Wednesday, May 26, 1999',
    time: '7:45 PM',
    kick_time: '7:45 PM',
    venue: 'Camp Nou',
    tv: 'RTE',
    referee: 'Pierluigi Collina',
    var: null,
    avar: null,
    assistant_referee_1: 'Gennaro Mazzei',
    assistant_referee_2: 'Claudio Puglisi',
    fourth_referee: 'Fiorenzo Treossi',
    reserve_ar: 'John Doe',
    timestamp: '1999-05-26 10:00:00 GMT',
  },
  home: { logo_url: 'man_utd_badge.png', name: 'Manchester United' },
  away: { logo_url: 'bayern_badge.png', name: 'Bayern Munich' },
  game_contacts: [
    {
      game_day_role: 'UEFA President',
      name: 'Lennart Johansson',
      cell_phone: '+551833242882',
      email: 'lennart@uefa.com',
    },
  ],
  kits: {
    away_goalkeeper: {
      jersey: { url: '/awayGoalkeeperJersey.jpg', color: 'Green' },
      shorts: { url: '/awayGoalkeeperShorts.jpg', color: 'Green' },
      socks: { url: '/awayGoalkeeperSocks.jpg', color: 'Green' },
    },
    away_player: {
      jersey: { url: '/awayPlayerJersey.jpg', color: 'Blue' },
      shorts: { url: '/awayPlayerShorts.jpg', color: 'Blue' },
      socks: { url: '/awayPlayerSocks.jpg', color: 'Blue' },
    },
    home_goalkeeper: {
      jersey: { url: '/homeGoalkeeperJersey.jpg', color: 'Purple' },
      shorts: { url: '/homeGoalKeeperShorts.jpg', color: 'Purple' },
      socks: { url: '/homeGoalkeeperSocks.jpg', color: 'Purple' },
    },
    home_player: {
      jersey: { url: '/homePlayerJersey.jpg', color: 'Red' },
      shorts: { url: '/homePlayerShorts.jpg', color: 'Red' },
      socks: { url: '/homePlayerSocks.jpg', color: 'Red' },
    },
    referee: {
      jersey: { url: '/refereeJersey.jpg', color: 'Black' },
      shorts: { url: '/refereeShorts.jpg', color: 'Black' },
      socks: { url: '/refereeSocks.jpg', color: 'Black' },
    },
  },
};
