// @flow

export const issueResponseWithScreeningAnswers = {
  // this response uses screening_answers and DOES NOT include conditional_fields_answers
  screening_answers: [
    {
      question_id: 231,
      screening_ruleset_version_id: 185,
      values: ['yes'],
    },
  ],
  coding: {
    osics_10: {
      osics_pathology_id: 654,
      osics_classification_id: 11,
      groups: ['lower_all', 'knee', 'all_injuries'],
      osics_body_area_id: 9,
      osics_id: 'KJAG',
      icd: 'NC93.62',
      side_id: 1,
    },
    clinical_impressions: {
      secondary_pathologies: [],
    },
  },
  occurrence_date: '2024-01-30',
  occurrence_min: null,
  issue_contact_type_id: null,
  injury_mechanism_id: null,
  issue_occurrence_title: '',
  activity_id: null,
  activity_type: 'nonfootball',
  association_period_id: null,
  athlete_id: 3392,
  closed: false,
  created_by: '',
  events: [
    {
      id: '',
      injury_status_id: 1,
      date: '2024-01-30',
    },
  ],
  examination_date: null,
  reported_date: null,
  game_id: '',
  has_recurrence: false,
  recurrence_id: null,
  continuation_issue_id: null,
  continuation_outside_system: false,
  has_supplementary_pathology: false,
  id: null,
  modification_info: null,
  annotations: [
    {
      annotationable_type: 'Athlete',
      annotationable_id: 3392,
      organisation_annotation_type_id: null,
      title: 'Initial Note',
      annotation_date: '2024-01-31T01:37:17+00:00',
      content: '',
      illness_occurrence_ids: [],
      injury_occurrence_ids: [],
      restricted_to_doc: false,
      restricted_to_psych: false,
      attachments_attributes: [],
      annotation_actions_attributes: [],
      attachments: [],
    },
  ],
  position_when_injured_id: 31,
  prior_resolved_date: null,
  session_completed: false,
  supplementary_pathology: '',
  total_duration: null,
  training_session_id: '',
  type_id: 3,
  concussion_assessments: [],
  unavailability_duration: null,
  bamic_site_id: null,
  bamic_grade_id: null,
  recurrence_outside_system: false,
  linked_issues: {
    illnesses: [],
    injuries: [],
  },
  attached_links: [],
  linked_chronic_issues: [],
  scope_to_org: true,
};

export const issueResponseWithConditionalFieldsAnswers = {
  // this response uses conditional_fields_answers and DOES NOT include screening_answers
  conditional_fields_answers: [
    {
      question_id: 231,
      screening_ruleset_version_id: 185,
      values: ['yes'],
    },
  ],
  coding: {
    osics_10: {
      osics_pathology_id: 654,
      osics_classification_id: 11,
      groups: ['lower_all', 'knee', 'all_injuries'],
      osics_body_area_id: 9,
      osics_id: 'KJAG',
      icd: 'NC93.62',
      side_id: 1,
    },
    clinical_impressions: {
      secondary_pathologies: [],
    },
  },
  occurrence_date: '2024-01-30',
  occurrence_min: null,
  issue_contact_type_id: null,
  injury_mechanism_id: null,
  issue_occurrence_title: '',
  activity_id: null,
  activity_type: 'nonfootball',
  association_period_id: null,
  athlete_id: 3392,
  closed: false,
  created_by: '',
  events: [
    {
      id: '',
      injury_status_id: 1,
      date: '2024-01-30',
    },
  ],
  examination_date: null,
  reported_date: null,
  game_id: '',
  has_recurrence: false,
  recurrence_id: null,
  continuation_issue_id: null,
  continuation_outside_system: false,
  has_supplementary_pathology: false,
  id: null,
  modification_info: null,
  annotations: [
    {
      annotationable_type: 'Athlete',
      annotationable_id: 3392,
      organisation_annotation_type_id: null,
      title: 'Initial Note',
      annotation_date: '2024-01-31T01:37:17+00:00',
      content: '',
      illness_occurrence_ids: [],
      injury_occurrence_ids: [],
      restricted_to_doc: false,
      restricted_to_psych: false,
      attachments_attributes: [],
      annotation_actions_attributes: [],
      attachments: [],
    },
  ],
  position_when_injured_id: 31,
  prior_resolved_date: null,
  session_completed: false,
  supplementary_pathology: '',
  total_duration: null,
  training_session_id: '',
  type_id: 3,
  concussion_assessments: [],
  unavailability_duration: null,
  bamic_site_id: null,
  bamic_grade_id: null,
  recurrence_outside_system: false,
  linked_issues: {
    illnesses: [],
    injuries: [],
  },
  attached_links: [],
  linked_chronic_issues: [],
  scope_to_org: true,
};

export const issuePanelStateWithConditionalFieldsAnswers = {
  addIssuePanel: {
    isOpen: true,
    title: '',
    initialInfo: {
      type: 'INJURY',
      athlete: 3392,
      athleteData: {
        addresses: [],
        age: null,
        allergy_names: ['test'],
        athlete_medical_alerts: [],
        availability: 'unavailable',
        country: 'United States',
        date_of_birth: null,
        email: 'uername@mail.com',
        emergency_contacts: [],
        extended_attributes: {},
        external_id: '367020fa-9ce8-470a-b5ba-48f0cb24e0b6',
        firstname: 'Phil',
        fullname: 'Phil Funk',
        height: null,
        id: 3392,
        insurance_policies: [],
        is_active: true,
        lastname: 'Funk',
        mobile_number: null,
        position: 'Unknown',
        position_group: 'Other',
        position_group_id: 4,
        position_group_order: 4,
        position_id: 31,
        short_external_id: '16971139393652105591',
        shortname: 'P. Funk',
        social_security_number: null,
        squad_names: [
          {
            id: 1,
            name: 'First Squad',
          },
        ],
        unresolved_issues_count: 20,
        avatar_url:
          'https://kitman-staging.imgix.net/avatar.jpg?auto=enhance&crop=faces&fit=crop&h=100&ixlib=rails-4.2.0&w=100',
        allergies: [],
        org_last_transfer_record: {
          transfer_type: 'Trade',
          joined_at: null,
          left_at: null,
          data_sharing_consent: true,
        },
        organisation_ids: [1],
        organisation_transfer_records: [
          {
            transfer_type: 'Trade',
            joined_at: null,
            left_at: null,
            data_sharing_consent: true,
          },
        ],
        constraints: {
          organisation_status: 'CURRENT_ATHLETE',
          active_periods: [
            {
              start: null,
              end: null,
            },
          ],
        },
      },
      diagnosisDate: '2024-01-30',
      reportedDate: null,
      chronicConditionOnsetDate: null,
      linkedChronicIssue: null,
      initialNote: '<p><br></p>',
      issueId: null,
      previousIssue: null,
      previousIssueId: null,
      continuationIssueId: null,
      recurrenceOutsideSystem: false,
      isAthleteSelectable: true,
    },
    diagnosisInfo: {
      coding: {
        osics_10: {
          osics_pathology_id: 654,
          osics_classification_id: 11,
          groups: ['lower_all', 'knee', 'all_injuries'],
          osics_body_area_id: 9,
          osics_id: 'KJAG',
          icd: 'NC93.62',
          side_id: 1,
        },
      },
      supplementaryCoding: {},
      supplementalPathology: null,
      examinationDate: null,
      onset: 3,
      onsetDescription: null,
      side: null,
      statuses: [
        {
          status: 1,
          date: '2024-01-30',
        },
      ],
      concussion_assessments: [],
      isBamic: false,
      bamicGrade: null,
      bamicSite: null,
      secondary_pathologies: [],
      onsetFreeText: '',
    },
    eventInfo: {
      diagnosisDate: '2024-01-30',
      event: 'other',
      eventType: 'nonfootball',
      activity: null,
      mechanismDescription: null,
      positionWhenInjured: 31,
      sessionCompleted: null,
      timeOfInjury: null,
      presentationType: null,
      injuryMechanismId: null,
      issueContactType: null,
      issueContactFreetext: '',
      events: {
        games: [],
        sessions: [],
      },
    },
    additionalInfo: {
      annotations: [],
      conditionalFieldsAnswers: [
        {
          question_id: 231,
          value: ['yes'],
          screening_ruleset_version_id: 185,
        },
      ],
      questions: [],
      requestStatus: null,
      linkedIssues: {
        illnesses: [],
        injuries: [],
      },
      issueLinks: [],
      issueFiles: [],
    },
    bamicGradesOptions: [],
    page: 4,
    requestStatus: 'loading',
    pathologyGroupRequestStatus: null,
    shouldRestoreData: false,
    issueCreateResponse: {
      id: 133529,
      activity_id: null,
      activity_type: 'nonfootball',
      occurrence_date: '2024-01-30T00:00:00+00:00',
      examination_date: null,
      association_period_id: null,
      occurrence_min: null,
      training_session_id: null,
      game_id: null,
      position_when_injured_id: 31,
      session_completed: false,
      created_by: 'Jergen Klopp',
      created_at: '2024-01-31T01:32:14+00:00',
      closed: false,
      supplementary_pathology: null,
      events: [
        {
          id: 323130,
          injury_status_id: 1,
          event_date: '2024-01-30T00:00:00+00:00',
          freetext_components: [],
          date: '2024-01-30T00:00:00+00:00',
        },
      ],
      issue_occurrence_title: null,
      reported_date: null,
      recurrence_outside_system: false,
      injury_mechanism_id: null,
      player_left_club: false,
      organisation_id: 1,
      freetext_components: [],
      continuation_issue: null,
      continuation_outside_system: false,
      archived: false,
      mechanism_description: null,
      onset_description: null,
      linked_chronic_issues: [],
      supplementary_coding: null,
      extended_attributes: [
        {
          id: 19,
          attribute_name: 'other_event_selection',
          value: 'nonfootball',
        },
      ],
      is_first_occurrence: true,
      is_last_occurrence: true,
      athlete_id: 3392,
      osics: {
        osics_id: 'WUPM',
        osics_pathology_id: 1394,
        osics_classification_id: 9,
        osics_body_area_id: 20,
        icd: 'NC54',
        bamic: null,
      },
      side_id: 1,
      bamic_grade_id: null,
      bamic_site_id: null,
      coding: {
        osics_10: {
          osics_id: 'WUPM',
          osics_pathology_id: 1394,
          osics_classification_id: 9,
          osics_body_area_id: 20,
          icd: 'NC54',
          bamic: null,
          side_id: 1,
        },
      },
      issue_id: 133467,
      type_id: 3,
      has_recurrence: false,
      events_order: [323130],
      diagnostics: [],
      notes: [],
      modification_info: '',
      total_duration: 1,
      unavailability_duration: 1,
      events_duration: {
        '323130': 1,
      },
      treatment_sessions: [],
      conditional_questions: [],
      linked_issues: [],
      annotations: [],
    },
  },
};
