// @flow
import {
  TIME_PERIODS,
  POPULATION_TYPES,
} from '@kitman/modules/src/analysis/shared/constants';
import { EMPTY_SELECTION } from '@kitman/components/src/Athletes/constants';

export const COMPARISON_WIDGET_MOCK = {
  id: 42611,
  rows: 5,
  cols: 6,
  vertical_position: 0,
  horizontal_position: 0,
  print_rows: 4,
  print_cols: 3,
  print_vertical_position: 6,
  print_horizontal_position: 3,
  rows_range: [4, 15],
  cols_range: [3, 6],
  widget_type: 'table',
  widget: {
    id: 1921,
    name: 'Comparison',
    table_container: {
      id: 1967,
      config: {
        table_type: 'COMPARISON',
        show_summary: true,
        table_sort: [
          {
            column_id: 5991,
            order_direction: 'HIGH_LOW',
          },
        ],
      },
      definitions: [],
      columns: [
        {
          id: 5991,
          column_id: '-4018997449497198732',
          name: '% Difference ',
          population: null,
          config: null,
          table_element: {
            id: 22500,
            name: '% Difference ',
            calculation: 'sum_absolute',
            config: null,
            data_source: {
              id: 6684,
              source: 'combination',
              variable: '%_difference',
              config: null,
              key_name: 'combination|%_difference',
              unit: '',
              type: 'TableMetric',
            },
          },
          time_scope: {
            time_period: TIME_PERIODS.thisSeason,
            start_time: null,
            end_time: null,
            time_period_length: null,
            time_period_length_offset: null,
          },
          order: 1,
        },
        {
          id: 5992,
          column_id: '4198073036950995169',
          name: 'CMJ Difference (%)',
          population: null,
          config: {
            conditional_formatting: [
              {
                type: 'numeric',
                condition: 'greater_than',
                value: 20,
                color: '#f3d2d5',
              },
            ],
            summary_calculation: 'median',
            pivot_locked: true,
          },
          table_element: {
            id: 22501,
            name: 'CMJ Difference (%)',
            calculation: 'max',
            config: null,
            data_source: {
              id: 6685,
              source: 'combination',
              variable: 'cmj_difference',
              config: null,
              key_name: 'combination|cmj_difference',
              unit: '%',
              type: 'TableMetric',
            },
          },
          time_scope: {
            time_period: TIME_PERIODS.thisSeason,
            start_time: null,
            end_time: null,
            time_period_length: null,
            time_period_length_offset: null,
          },
          order: 2,
        },
        {
          id: 6006,
          column_id: '3676992813905959320',
          name: 'Last Game Score ',
          population: null,
          config: null,
          table_element: {
            id: 22507,
            name: 'Last Game Score ',
            calculation: 'sum',
            config: null,
            data_source: {
              id: 6701,
              source: 'combination',
              variable: 'last_game_score',
              config: null,
              key_name: 'combination|last_game_score',
              unit: '',
              type: 'TableMetric',
            },
          },
          time_scope: {
            time_period: TIME_PERIODS.thisSeason,
            start_time: null,
            end_time: null,
            time_period_length: null,
            time_period_length_offset: null,
          },
          order: 3,
        },
      ],
      rows: [
        {
          id: 75983,
          row_id: '125174429168371732',
          name: null,
          population: {
            athletes: [],
            positions: [],
            position_groups: [25],
            squads: [],
            applies_to_squad: false,
            all_squads: false,
          },
          config: null,
          table_element: null,
          time_scope: {},
          order: 1,
        },
        {
          id: 75985,
          row_id: '2929530489591280397',
          name: null,
          population: {
            athletes: [36479],
            positions: [],
            position_groups: [],
            squads: [],
            applies_to_squad: false,
            all_squads: false,
          },
          config: null,
          table_element: null,
          time_scope: {},
          order: 3,
        },
        {
          id: 76070,
          row_id: '3611065962999068529',
          name: null,
          population: {
            athletes: [],
            positions: [],
            position_groups: [],
            squads: [],
            applies_to_squad: true,
            all_squads: false,
          },
          config: null,
          table_element: null,
          time_scope: {},
          order: 5,
        },
      ],
    },
  },
  widget_render: {
    name: 'Comparison',
  },
};

export const LONGITUDINAL_WIDGET_MOCK = {
  id: 42613,
  rows: 5,
  cols: 6,
  vertical_position: 21,
  horizontal_position: 0,
  print_rows: 4,
  print_cols: 3,
  print_vertical_position: 6,
  print_horizontal_position: 0,
  rows_range: [4, 15],
  cols_range: [3, 6],
  widget_type: 'table',
  widget: {
    id: 1923,
    name: 'Longitudinal',
    table_container: {
      id: 1969,
      config: {
        table_type: 'LONGITUDINAL',
        show_summary: true,
        column_width_type: 'FIT_TO_WIDTH',
        table_sort: [
          {
            column_id: 5995,
            order_direction: 'HIGH_LOW',
          },
        ],
      },
      definitions: [],
      columns: [
        {
          id: 5995,
          column_id: '-621718536497242753',
          name: 'CMJ Difference (%)',
          population: {
            athletes: [],
            positions: [],
            position_groups: [],
            squads: [],
            applies_to_squad: true,
            all_squads: false,
          },
          config: {
            conditional_formatting: [
              {
                type: 'numeric',
                condition: 'greater_than',
                value: 2,
                color: '#f3d2d5',
              },
            ],
            summary_calculation: 'percentageFilled',
            pivot_locked: false,
          },
          table_element: {
            id: 22504,
            name: 'CMJ Difference (%)',
            calculation: 'sum',
            config: null,
            data_source: {
              id: 6688,
              source: 'combination',
              variable: 'cmj_difference',
              config: null,
              key_name: 'combination|cmj_difference',
              unit: '%',
              type: 'TableMetric',
            },
          },
          time_scope: {},
          order: 1,
        },
        {
          id: 6005,
          column_id: '4572076510677596245',
          name: 'Testing 20210423130225 (%)',
          population: {
            athletes: [],
            positions: [],
            position_groups: [],
            squads: [],
            applies_to_squad: true,
            all_squads: false,
          },
          config: {
            summary_calculation: 'range',
            pivot_locked: false,
          },
          table_element: {
            id: 22506,
            name: 'Testing 20210423130225 (%)',
            calculation: 'sum',
            config: null,
            data_source: {
              id: 6700,
              source: 'kitman:injury_risk',
              variable: 'e7a27f18-51cf-4882-97ad-e2bc59b5fb67',
              config: null,
              key_name:
                'kitman:injury_risk|e7a27f18-51cf-4882-97ad-e2bc59b5fb67',
              unit: '',
              type: 'TableMetric',
            },
          },
          time_scope: {},
          order: 1,
        },
        {
          id: 6013,
          column_id: '-1195868676430384985',
          name: '% Difference ',
          population: {
            athletes: [],
            positions: [],
            position_groups: [25],
            squads: [],
            applies_to_squad: false,
            all_squads: false,
          },
          config: {
            summary_calculation: 'range',
            pivot_locked: false,
          },
          table_element: {
            id: 22589,
            name: '% Difference ',
            calculation: 'min_absolute',
            config: null,
            data_source: {
              id: 6704,
              source: 'combination',
              variable: '%_difference',
              config: null,
              key_name: 'combination|%_difference',
              unit: '',
              type: 'TableMetric',
            },
          },
          time_scope: {},
          order: 3,
        },
      ],
      rows: [
        {
          id: 75989,
          row_id: '1707279048580450049',
          name: null,
          population: null,
          config: null,
          table_element: null,
          time_scope: {
            time_period: TIME_PERIODS.thisSeason,
            start_time: null,
            end_time: null,
            time_period_length: null,
            time_period_length_offset: null,
          },
          order: 1,
        },
      ],
    },
  },
};

export const SCORECARD_WIDGET_MOCK = {
  id: 42612,
  rows: 5,
  cols: 6,
  vertical_position: 26,
  horizontal_position: 0,
  print_rows: 4,
  print_cols: 3,
  print_vertical_position: 10,
  print_horizontal_position: 0,
  rows_range: [4, 15],
  cols_range: [3, 6],
  widget_type: 'table',
  widget: {
    id: 1922,
    name: 'Scorecard',
    table_container: {
      id: 1968,
      config: {
        table_type: 'SCORECARD',
        show_summary: true,
        column_width_type: 'FIT_TO_WIDTH',
        table_sort: [
          {
            column_id: 6012,
            order_direction: 'HIGH_LOW',
          },
        ],
      },
      definitions: [],
      columns: [
        {
          id: 5993,
          column_id: '-4446382244125431444',
          name: null,
          population: {
            athletes: [],
            positions: [],
            position_groups: [25],
            squads: [],
            applies_to_squad: false,
            all_squads: false,
          },
          config: {
            pivot_locked: false,
          },
          table_element: null,
          time_scope: {
            time_period: TIME_PERIODS.thisSeason,
            start_time: null,
            end_time: null,
            time_period_length: null,
            time_period_length_offset: null,
          },
          order: 1,
        },
        {
          id: 6012,
          column_id: '4180431092596044232',
          name: null,
          population: {
            athletes: [],
            positions: [],
            position_groups: [],
            squads: [],
            applies_to_squad: true,
            all_squads: false,
          },
          config: null,
          table_element: null,
          time_scope: {
            time_period: TIME_PERIODS.thisSeason,
            start_time: null,
            end_time: null,
            time_period_length: null,
            time_period_length_offset: null,
          },
          order: 2,
        },
        {
          id: 6011,
          column_id: '-2991534247513120800',
          name: null,
          population: {
            athletes: [15642],
            positions: [],
            position_groups: [],
            squads: [],
            applies_to_squad: false,
            all_squads: false,
          },
          config: null,
          table_element: null,
          time_scope: {
            time_period: TIME_PERIODS.today,
            start_time: null,
            end_time: null,
            time_period_length: null,
            time_period_length_offset: null,
          },
          order: 3,
        },
      ],
      rows: [
        {
          id: 75986,
          row_id: '3769756312923531661',
          name: 'CMJ Difference (%)',
          population: null,
          config: null,
          table_element: {
            id: 22502,
            name: 'CMJ Difference (%)',
            calculation: 'max',
            config: null,
            data_source: {
              id: 6686,
              source: 'combination',
              variable: 'cmj_difference',
              config: null,
              key_name: 'combination|cmj_difference',
              unit: '%',
              type: 'TableMetric',
            },
          },
          time_scope: {},
          order: 1,
        },
        {
          id: 75987,
          row_id: '-99493752435515971',
          name: 'Left Thigh Stiffness ',
          population: null,
          config: {
            summary_calculation: 'empty',
          },
          table_element: {
            id: 22503,
            name: 'Left Thigh Stiffness ',
            calculation: 'max',
            config: null,
            data_source: {
              id: 6687,
              source: 'combination',
              variable: 'left_thigh_stiffness',
              config: null,
              key_name: 'combination|left_thigh_stiffness',
              unit: '',
              type: 'TableMetric',
            },
          },
          time_scope: {},
          order: 2,
        },
        {
          id: 75988,
          row_id: '1259162668098492848',
          name: '% Difference ',
          population: null,
          config: null,
          table_element: {
            id: 22505,
            name: '% Difference ',
            calculation: 'min',
            config: null,
            data_source: {
              id: 6689,
              source: 'combination',
              variable: '%_difference',
              config: null,
              key_name: 'combination|%_difference',
              unit: '',
              type: 'TableMetric',
            },
          },
          time_scope: {},
          order: 3,
        },
        {
          id: 75991,
          row_id: '-4468487474714027935',
          name: 'CMJ Difference (%)',
          population: null,
          config: {
            summary_calculation: 'range',
          },
          table_element: {
            id: 22509,
            name: 'CMJ Difference (%)',
            calculation: 'min_absolute',
            config: null,
            data_source: {
              id: 6703,
              source: 'combination',
              variable: 'cmj_difference',
              config: null,
              key_name: 'combination|cmj_difference',
              unit: '%',
              type: 'TableMetric',
            },
          },
          time_scope: {},
          order: 4,
        },
      ],
    },
  },
  widget_render: {
    name: 'Scorecard',
    isLoading: false,
    error: false,
  },
};

export const COLUMN_FORMULA_PANEL_STATE = {
  isEditMode: false,
  isOpen: false,
  mode: 'create',
  columnName: '% baseline change',
  formulaId: 2,
  widgetType: 'COMPARISON',
  widgetId: 172306,
  tableContainerId: 12,
  columnId: null,
  progressStep: 2,
  inputs: {
    A: {
      panel_source: 'metric',
      dataSource: {
        type: 'TableMetric',
        key_name: 'kitman|training_session_minutes',
        source: 'kitman',
        variable: 'training_session_minutes',
      },
      population: null,
      time_scope: {
        time_period: 'this_season_so_far',
      },
      calculation: 'sum',
      input_params: null,
      element_config: {
        filters: {
          time_loss: [],
          competitions: [],
          event_types: [],
          session_type: [],
          training_session_types: [],
          match_days: [],
        },
        calculation_params: {},
      },
      population_selection: null,
      isPanelFiltersOpen: false,
    },
    B: {
      panel_source: 'metric',
      dataSource: {
        type: 'TableMetric',
        key_name: 'kitman|training_session_minutes',
        source: 'kitman',
        variable: 'training_session_minutes',
      },
      population: {
        applies_to_squad: false,
        all_squads: false,
        position_groups: [],
        positions: [],
        athletes: [],
        squads: [3510],
        context_squads: [3510],
        users: [],
        labels: [],
        segments: [],
      },
      time_scope: {
        time_period: 'this_season_so_far',
      },
      calculation: 'sum',
      input_params: null,
      element_config: {
        filters: {
          time_loss: [],
          competitions: [],
          event_types: [],
          session_type: [],
          training_session_types: [],
          match_days: [],
        },
        calculation_params: {},
      },
      population_selection: 'select',
      isPanelFiltersOpen: false,
    },
  },
};

export const ADD_FORMULA_COLUMN_MOCK = {
  name: '% baseline change',
  data_source_type: 'Formula',
  input_params: {
    A: {
      data_source_type: 'TableMetric',
      population: null,
      time_scope: { time_period: 'this_season_so_far' },
      calculation: 'sum',
      input_params: { variable: 'training_session_minutes', source: 'kitman' },
      element_config: {},
    },
    B: {
      data_source_type: 'TableMetric',
      population: {
        applies_to_squad: false,
        all_squads: false,
        position_groups: [],
        positions: [],
        athletes: [],
        squads: [3510],
        context_squads: [3510],
        users: [],
        labels: [],
        segments: [],
      },
      time_scope: { time_period: 'this_season_so_far' },
      calculation: 'sum',
      input_params: { variable: 'training_session_minutes', source: 'kitman' },
      element_config: {},
    },
  },
  summary: 'formula',
  time_scope: { time_period: 'this_season_so_far' },
  element_config: {
    formula: '(B-A)/A * 100',
    formula_id: 2,
  },
};

export const ADD_FORMULA_CHART_MOCK = {
  id: 123,
  data_source_type: 'Formula',
  calculation: 'formula',
  overlays: null,
  input_params: ADD_FORMULA_COLUMN_MOCK.input_params,
  population: { ...EMPTY_SELECTION },
  time_scope: { time_period: 'this_season_so_far' },
  config: {
    formula: '(B-A)/A * 100',
    render_options: {
      name: '% baseline change',
      type: 'value',
      axis_config: 'left',
    },
    inherit_groupings: true,
    groupings: [],
  },
};

export const ACTIVE_FORMULA_MOCK = {
  id: 2,
  label: '% baseline change',
  formula_expression: '(B-A)/A * 100',
  inputs: [
    {
      id: 'A',
      label: 'Set baseline',
      description: 'baseline',
      population_config: {
        supported_types: [POPULATION_TYPES.inherit, POPULATION_TYPES.squad],
        single_type_selection: true,
        default_value: POPULATION_TYPES.inherit,
      },
    },
    {
      id: 'B',
      label: 'Add comparison',
      description: 'comparison',
      population_config: {
        supported_types: [POPULATION_TYPES.inherit, POPULATION_TYPES.squad],
        single_type_selection: true,
        default_value: POPULATION_TYPES.inherit,
      },
    },
  ],
};

export const CONVERTED_FORMULA_DATASOURCE = {
  A: {
    calculation: 'sum',
    dataSource: {
      ids: [],
      key_name: 'kitman|training_session_minutes',
      source: 'kitman',
      status: undefined,
      subtypes: {},
      type: 'TableMetric',
      variable: 'training_session_minutes',
    },
    element_config: {},
    isPanelFiltersOpen: false,
    panel_source: 'metric',
    population: null,
    population_selection: 'inherit',
    time_scope: {
      time_period: 'this_season_so_far',
    },
  },
  B: {
    calculation: 'sum',
    dataSource: {
      ids: [],
      key_name: 'kitman|training_session_minutes',
      source: 'kitman',
      status: undefined,
      subtypes: {},
      type: 'TableMetric',
      variable: 'training_session_minutes',
    },
    element_config: {},
    isPanelFiltersOpen: false,
    panel_source: 'metric',
    population: {
      all_squads: false,
      applies_to_squad: false,
      athletes: [],
      context_squads: [3510],
      labels: [],
      position_groups: [],
      positions: [],
      segments: [],
      squads: [3510],
      users: [],
    },
    population_selection: 'select',
    time_scope: {
      time_period: 'this_season_so_far',
    },
  },
};

export const TABLE_DYNAMIC_ROWS = [
  {
    id: 25,
    row_id: '2425',
    isDynamic: true,
    children: [
      {
        id: 'Athlete 1',
        row_id: '12345',
        value: '7',
      },
      {
        id: 'Athlete 2',
        row_id: '1245',
        value: '9',
      },
      {
        id: 'Athlete 3',
        row_id: '124',
        value: '9',
      },
    ],
    population: {
      applies_to_squad: false,
      position_groups: [25],
      positions: [],
      athletes: [],
      all_squads: false,
      squads: [],
      context_squads: [8],
      children: [],
    },
  },
];

export const TABLE_DATA = {
  rows: [
    {
      id: 1,
      row_id: 'row_1',
    },
    {
      id: 2,
      row_id: 'row_2',
      config: { groupings: ['squad'] },
    },
    {
      id: 3,
      row_id: 'row_3',
    },
  ],
  columns: [
    {
      id: 1,
      column_id: 'col_1',
      config: {
        ranking_calculation: {
          type: 'RANK',
          direction: 'HIGH_LOW',
        },
      },
      summary: 'sum',
      data: {
        row_1: { value: 5 },
        row_2: { forward: { value: 10 }, 'Loose-head Prop': { value: 5 } },
        row_3: { value: 2 },
      },
    },
  ],
};
