// @flow
import getClubSquads from '@kitman/services/src/services/getClubSquads';
import updateGameInformation from '@kitman/modules/src/PlanningHub/src/services/updateGameInformation';
import confirmFileUpload from './services/uploads/confirmFileUpload';
import copyRehabSessionExercises from './services/rehab/copyRehabSessionExercises';
import createAssessmentGroup from './services/assessmentGroup/createAssessmentGroup';
import createOfficial from './services/createOfficial';
import createRehabSession from './services/rehab/createRehabSession';
import editOfficial from './services/editOfficial';
import filterRehabSessions from './services/rehab/filterRehabSessions';
import updateExercise from './services/rehab/updateExercise';
import getDocumentNoteCategories from './services/getDocumentNoteCategories';
import saveAnnotation from './services/saveAnnotation';
import updateAnnotation from './services/updateAnnotation';
import getAssessmentTemplates from './services/getAssessmentTemplates';
import getAssessmentGroups from './services/assessmentGroup/getAssessmentGroups';
import getAthleteReviewTypes from './services/getAthleteReviewTypes';
import getDashboards from './services/getDashboards';
import getExercises from './services/rehab/getExercises';
import getExercisesById from './services/rehab/getExercisesById';
import getInitialData from './services/getInitialData';
import getInjuryStatuses from './services/getInjuryStatuses';
import getFieldConditions from './services/planning/getFieldConditions';
import getPermissions from './services/getPermissions';
import getPreferences from './services/getPreferences';
import getSport from './services/getSport';
import getTerminologies from './services/getTerminologies';
import getAthleteData from './services/getAthleteData';
import getAthletesPolicies from './services/getAthletesPolicies';
import getAdministrationAthleteData from './services/getAdministrationAthleteData';
import getInternationalPhonePrefixes from './services/getInternationalPhonePrefixes';
import getPositionGroups from './services/getPositionGroups';
import getSquadAthletes from './services/getSquadAthletes';
import getSquadAthleteSearch from './services/getSquadAthleteSearch';
import getVenueTypes from './services/getVenueTypes';
import getCompetitions from './services/getCompetitions';
import getOrganisation from './services/getOrganisation';
import getOrganisationTeams from './services/getOrganisationTeams';
import getOrganisationVariations from './services/rehab/getOrganisationVariations';
import getRehabExercise from './services/rehab/getRehabExercise';
import getRehabNotes from './services/rehab/getRehabNotes';
import getRehabSessions from './services/rehab/getRehabSessions';
import getRelationTypes from './services/getRelationTypes';
import getSquads from './services/getSquads';
import getWorkloadTypes from './services/getWorkloadTypes';
import getEventConditions from './services/getEventConditions';
import getParticipationLevels from './services/getParticipationLevels';
import getSessionTypes from './services/getSessionTypes';
import getTeams from './services/getTeams';
import formAnswerSetsDelete from './services/formAnswerSetsDelete';
import getFormDataSourceItems from './services/getFormDataSourceItems';
import deleteExercise from './services/rehab/deleteExercise';
import deleteSession from './services/rehab/deleteSession';
import getCurrentUser from './services/getCurrentUser';
import getTurnarounds from './services/getTurnarounds';
import getGameStatuses from './services/getGameStatuses';
import getSquadNames from './services/getSquadNames';
import getClubs from './services/getClubs';
import getAssociationsOrgs from './services/getAssociationsOrgs';
import getDivisions from './services/getDivisions';
import searchContacts from './services/contacts/searchContacts';
import getContactRoles from './services/contacts/getContactRoles';
import createContact from './services/contacts/createContact';
import updateContact from './services/contacts/updateContact';
import deleteContact from './services/contacts/deleteContact';
import createLeagueFixture from './services/planning/createLeagueFixture';
import createMatchDayPdf from './services/planning/createMatchDayPdf';
import getTrainingVariables from './services/getTrainingVariables';
import getBodyAreasMultiCodingV2 from './services/medical/pathologies/getBodyAreasMultiCodingV2';
import getPathologiesMultiCodingV2 from './services/medical/pathologies/getPathologiesMultiCodingV2';
import getPathologiesByIds from './services/medical/pathologies/getPathologiesByIds';

import linkMaintenanceExerciseToSession from './services/rehab/linkMaintenanceExerciseToSession';
import { getCountries } from './services/general';
import {
  getFavorites,
  makeFavorite,
  deleteFavorite,
} from './services/favoriting';
import {
  getInjuryOsics,
  getIllnessOsics,
  getInjuryOsicsPathologies,
  getIllnessOsicsPathologies,
  getInjuryOsicsClassifications,
  getIllnessOsicsClassifications,
  getInjuryOsicsBodyAreas,
  getIllnessOsicsBodyAreas,
  getCodingSystemV2Classifications,
} from './services/medical/osics';
import {
  getClinicalImpressionsBodyAreas,
  getClinicalImpressionsClassifications,
} from './services/medical/clinicalImpressions';
import {
  getDatalysBodyAreas,
  getDatalysClassifications,
} from './services/medical/datalys';
import {
  updateNflParticipationLevels,
  getMatchDayTemplateData,
} from './services/planning';
import getOrgCustomEquipmentTypes from './services/planning/getOrgCustomEquipment';
import getOrgCustomLocations from './services/planning/getOrgCustomLocations';
import getOrgCustomSurfaceTypes from './services/planning/getOrgCustomSurfaceTypes';
import getParticipationLevelReasons from './services/planning/getParticipationLevelReasons';
import getSurfaceCompositionsByFieldType from './services/planning/getSurfaceCompositionsByFieldType';
import getActivityLocations from './services/planning/getActivityLocations';
import getFixtureRatings from './services/planning/getFixtureRatings';
import getOrganisationFormats from './services/planning/getOrganisationFormats';
import getActiveSquad from './services/getActiveSquad';
import getPermittedSquads from './services/getPermittedSquads';
import getSquadAthletesById from './services/getSquadAthletesById';
import getMetricVariables from './services/getMetricVariables';
import getAreCoachingPrinciplesEnabled from './services/getAreCoachingPrinciplesEnabled';
import getIsActivityTypeCategoriesEnabled from './services/getIsActivityTypeCategoriesEnabled';
import getCurrentAssociation from './services/getCurrentAssociation';
import putFileToPresignedUrl from './services/uploads/putFileToPresignedUrl';
import unlockAccess from './services/unlockAccess';
import uploadWithPresignedPost from './services/uploads/uploadWithPresignedPost';
import fetchOrganisationPreference from './services/fetchOrganisationPreference';
import bulkUpdateEventRequests from './services/leaguefixtures/bulkUpdateEventRequests';

import {
  archiveAllergy,
  archiveAttachment,
  archiveDiagnostic,
  archiveDocument,
  archiveMedicalAlert,
  archiveMedicalDocument,
  archiveMedicalNote,
  archiveMedication,
  archiveProcedure,
  bulkUpdateNotes,
  createCustomDrug,
  createIssueEvent,
  createJob,
  deleteDiagnosticAttachment,
  deleteLastEvent,
  deleteProcedureAttachment,
  dispenseMedication,
  expireModificationNote,
  expireNote,
  exportCombinedAnkleSupport,
  exportFormAnswerSets,
  exportInjuryDetailReport,
  exportInjuryMedicationReport,
  exportInjurySurveillanceReport,
  exportMedicationsReport,
  exportOsha300Report,
  exportTimeLossAllActivitiesReport,
  exportTimeLossBodyPartReport,
  getActivityGroups,
  getAllergies,
  getAllergyMedications,
  getAncillaryEligibleRanges,
  getAnnotationAuthors,
  getAnnotationMedicalTypes,
  getArchiveMedicalFlagReasons,
  getArchiveMedicalNoteReasons,
  getArchiveMedicationReasons,
  getArchiveReasons,
  getAthleteChronicIssues,
  getAthleteConcussionAssessmentResults,
  getAthleteContinuationIssues,
  getAthleteIssue,
  getAthleteIssues,
  getAthleteMedicalAlerts,
  getAthleteMedications,
  getAthleteRoster,
  getCoachesReportData,
  getCodingSystemIdentifiers,
  getConcussionFormAnswersSetsList,
  getConcussionFormTypes,
  getConcussionInjuryList,
  getContactTypes,
  getCovidAntibodyResultTypes,
  getCovidResultTypes,
  getCurrentAllergy,
  getCurrentMedicalAlert,
  getCurrentProcedure,
  getDiagnosticReasons,
  getDiagnosticResultTypes,
  getDiagnostics,
  getDiagnosticStatuses,
  getDiagnosticTypeGroupSets,
  getDiagnosticTypes,
  getDrFirstMedications,
  getDrugForms,
  getDrugLots,
  getDrugStocks,
  getExaminerUsers,
  getFormResults,
  getGameAndTrainingOptions,
  getGrades,
  getGroupsForPathology,
  getIllnessOnset,
  getInjuryMechanisms,
  getInjuryOnset,
  getLastNote,
  getMedicalAlerts,
  getMedicalAttachmentCategories,
  getMedicalAttachmentsEntityTypes,
  getMedicalAttachmentsFileTypes,
  getMedicalDocument,
  getMedicalDocuments,
  getMedicalIssues,
  getMedicalLocations,
  getMedicalNotes,
  getMedicationListSources,
  getMedications,
  getMedStrengthUnits,
  getModificationAuthors,
  getModificationNotes,
  getModificationType,
  getNonMedicalAllergies,
  getNotificationsIFrame,
  getOrderProviders,
  getOsicsInfo,
  getPastAthletes,
  getPresentationTypes,
  getProcedures,
  getProceduresFormData,
  getProcedureTypes,
  getReopeningReasons,
  getReportColumns,
  getSides,
  getStaffUsers,
  getStockMedications,
  getTreatments,
  getTreatmentSessionOptions,
  getTryoutAthletes,
  patchTreatment,
  removeDrugStock,
  resolveChronicIssue,
  saveAllergyMedication,
  saveAncillaryRange,
  saveAttachmentLegacy,
  saveBulkMedicalNotes,
  saveChronicIssue,
  saveConcussionTestResults,
  saveDiagnostic,
  saveDiagnosticAttachment,
  saveDiagnosticLinks,
  saveDocument,
  saveDraftWorkersComp,
  saveDrugStock,
  saveIssue,
  saveMedicalAlert,
  saveMedicalNote,
  saveMedicationEndDate,
  saveModificationNote,
  saveNote,
  savePlayerHasLeftClub,
  saveProcedure,
  saveProcedureAttachment,
  saveReconciledDiagnostic,
  saveRedoxReviewed,
  saveReviewedDiagnostics,
  saveTreatment,
  screenAllergyToDrug,
  screenDrugToDrug,
  searchCoding,
  searchDiagnosticTypes,
  searchDrugs,
  searchDrugsFavorites,
  searchMedicalEntityAttachments,
  searchOrgAthletes,
  searchProcedureTypes,
  setCoachesReportComment,
  splitDocument,
  submitWorkersComp,
  updateAllergy,
  updateAthleteIssueType,
  updateAttachment,
  updateDiagnostic,
  updateFormAnswersSetLinkedIssues,
  updateLastEvent,
  updateMedicalAlert,
  updateMedicalDocument,
  updateMedication,
  updateProcedure,
  uploadFile,
  getAthletesAvailabilities,
} from './services/medical';
import {
  getExportBilling,
  exportDemographicReport,
  exportDiagnosticBilling,
  exportDiagnosticsRecords,
  exportMedicationRecords,
  exportNullDataReport,
  exportQualityReports,
  exportTreatmentBilling,
  exportHapAuthStatus,
  exportParticipantExposure,
  exportConcussionBaselineAudit,
  exportHapCovidBranch,
} from './services/exports';
import {
  getMatchReportNotes,
  saveMatchReportNotes,
  getDisciplinaryReasons,
  resetMatchReport,
  saveMatchReportScores,
  createUserEventRequest,
  getUserEventRequests,
  deleteUserEventRequest,
  updateUserEventRequest,
  getUserEventRequestRejectReasons,
  assignMatchMonitor,
} from './services/leaguefixtures';
import {
  getAthletePlayTimes,
  bulkUpdateAthletePlayTimes,
  createCustomOppositionName,
  updateCustomOppositionName,
  deleteCustomOppositionName,
} from './services/planningEvent';
import { getUserSquadHistory } from './services/getUserSquadHistory';
import createKitMatrix from './services/kitMatrix/createKitMatrix';
import updateKitMatrix from './services/kitMatrix/updateKitMatrix';
import searchKitMatrices from './services/kitMatrix/searchKitMatrices';
import getKitMatrixColors from './services/kitMatrix/getKitMatrixColors';
import getLeagueSeasons from './services/kitMatrix/getLeagueSeasons';
import sendMatchNoticeEmail from './services/notifications/sendMatchNoticeEmail';
import searchEmails from './services/notifications/searchEmails';

export {
  archiveAllergy,
  archiveAttachment,
  archiveDiagnostic,
  archiveDocument,
  archiveMedicalAlert,
  archiveMedicalDocument,
  archiveMedicalNote,
  archiveMedication,
  archiveProcedure,
  assignMatchMonitor,
  bulkUpdateAthletePlayTimes,
  bulkUpdateNotes,
  confirmFileUpload,
  copyRehabSessionExercises,
  createAssessmentGroup,
  createContact,
  createCustomDrug,
  createCustomOppositionName,
  createIssueEvent,
  createJob,
  createKitMatrix,
  createLeagueFixture,
  createMatchDayPdf,
  createOfficial,
  createRehabSession,
  createUserEventRequest,
  deleteContact,
  deleteCustomOppositionName,
  deleteDiagnosticAttachment,
  deleteExercise,
  deleteFavorite,
  deleteLastEvent,
  deleteProcedureAttachment,
  deleteSession,
  deleteUserEventRequest,
  dispenseMedication,
  editOfficial,
  expireModificationNote,
  expireNote,
  exportCombinedAnkleSupport,
  exportConcussionBaselineAudit,
  exportDemographicReport,
  exportDiagnosticBilling,
  exportDiagnosticsRecords,
  exportFormAnswerSets,
  exportHapAuthStatus,
  exportHapCovidBranch,
  exportInjuryDetailReport,
  exportInjuryMedicationReport,
  exportInjurySurveillanceReport,
  exportMedicationRecords,
  exportMedicationsReport,
  exportNullDataReport,
  exportOsha300Report,
  exportParticipantExposure,
  exportQualityReports,
  exportTimeLossAllActivitiesReport,
  exportTimeLossBodyPartReport,
  exportTreatmentBilling,
  fetchOrganisationPreference,
  filterRehabSessions,
  formAnswerSetsDelete,
  getActiveSquad,
  getActivityGroups,
  getActivityLocations,
  getAdministrationAthleteData,
  getAllergies,
  getAllergyMedications,
  getAncillaryEligibleRanges,
  getAnnotationAuthors,
  getAnnotationMedicalTypes,
  getArchiveMedicalFlagReasons,
  getArchiveMedicalNoteReasons,
  getArchiveMedicationReasons,
  getArchiveReasons,
  getAssessmentGroups,
  getAssessmentTemplates,
  getAssociationsOrgs,
  getAthleteChronicIssues,
  getAthleteConcussionAssessmentResults,
  getAthleteContinuationIssues,
  getAthleteData,
  getAthleteIssue,
  getAthleteIssues,
  getAthleteMedicalAlerts,
  getAthleteMedications,
  getAthletePlayTimes,
  getAthleteReviewTypes,
  getAthleteRoster,
  getAthletesAvailabilities,
  getAthletesPolicies,
  getBodyAreasMultiCodingV2,
  getClinicalImpressionsBodyAreas,
  getClinicalImpressionsClassifications,
  getClubs,
  getClubSquads,
  getCoachesReportData,
  getCodingSystemIdentifiers,
  getCompetitions,
  getConcussionFormAnswersSetsList,
  getConcussionFormTypes,
  getConcussionInjuryList,
  getContactRoles,
  getContactTypes,
  getCountries,
  getCovidAntibodyResultTypes,
  getCovidResultTypes,
  getCurrentAllergy,
  getCurrentAssociation,
  getCurrentMedicalAlert,
  getCurrentProcedure,
  getCurrentUser,
  getDashboards,
  getDatalysBodyAreas,
  getDatalysClassifications,
  getDiagnosticReasons,
  getDiagnosticResultTypes,
  getDiagnostics,
  getDiagnosticStatuses,
  getDiagnosticTypeGroupSets,
  getDiagnosticTypes,
  getDisciplinaryReasons,
  getDivisions,
  getDocumentNoteCategories,
  getDrFirstMedications,
  getDrugForms,
  getDrugLots,
  getDrugStocks,
  getEventConditions,
  getExaminerUsers,
  getExercises,
  getExercisesById,
  getExportBilling,
  getFavorites,
  getFieldConditions,
  getFixtureRatings,
  getFormDataSourceItems,
  getFormResults,
  getGameAndTrainingOptions,
  getGameStatuses,
  getGrades,
  getGroupsForPathology,
  getIllnessOnset,
  getIllnessOsics,
  getIllnessOsicsBodyAreas,
  getIllnessOsicsClassifications,
  getIllnessOsicsPathologies,
  getInitialData,
  getInjuryMechanisms,
  getInjuryOnset,
  getInjuryOsics,
  getInjuryOsicsBodyAreas,
  getInjuryOsicsClassifications,
  getInjuryOsicsPathologies,
  getInjuryStatuses,
  getInternationalPhonePrefixes,
  getIsActivityTypeCategoriesEnabled,
  getAreCoachingPrinciplesEnabled,
  getKitMatrixColors,
  getLeagueSeasons,
  getLastNote,
  getMatchReportNotes,
  getMedicalAlerts,
  getMedicalAttachmentCategories,
  getMedicalAttachmentsEntityTypes,
  getMedicalAttachmentsFileTypes,
  getMedicalDocument,
  getMedicalDocuments,
  getMedicalIssues,
  getMedicalLocations,
  getMedicalNotes,
  getMedicationListSources,
  getMedications,
  getMedStrengthUnits,
  getMetricVariables,
  getModificationAuthors,
  getModificationNotes,
  getModificationType,
  getNonMedicalAllergies,
  getNotificationsIFrame,
  getOrderProviders,
  getOrganisation,
  getOrganisationFormats,
  getOrganisationTeams,
  getOrganisationVariations,
  getOrgCustomEquipmentTypes,
  getOrgCustomLocations,
  getOrgCustomSurfaceTypes,
  getCodingSystemV2Classifications,
  getOsicsInfo,
  getParticipationLevelReasons,
  getParticipationLevels,
  getPastAthletes,
  getPathologiesMultiCodingV2,
  getPermissions,
  getPathologiesByIds,
  getPermittedSquads,
  getPositionGroups,
  getPreferences,
  getPresentationTypes,
  getProcedures,
  getProceduresFormData,
  getProcedureTypes,
  getRehabExercise,
  getRehabNotes,
  getRehabSessions,
  getRelationTypes,
  getReopeningReasons,
  getReportColumns,
  getSessionTypes,
  getSides,
  getSport,
  getSquadAthletes,
  getSquadAthletesById,
  getSquadAthleteSearch,
  getSquadNames,
  getSquads,
  getStaffUsers,
  getStockMedications,
  getSurfaceCompositionsByFieldType,
  getTeams,
  getTerminologies,
  getTreatments,
  getTreatmentSessionOptions,
  getTryoutAthletes,
  getTurnarounds,
  getUserEventRequests,
  getUserEventRequestRejectReasons,
  getUserSquadHistory,
  getVenueTypes,
  getWorkloadTypes,
  linkMaintenanceExerciseToSession,
  makeFavorite,
  patchTreatment,
  putFileToPresignedUrl,
  removeDrugStock,
  resetMatchReport,
  resolveChronicIssue,
  saveAllergyMedication,
  saveAncillaryRange,
  saveAnnotation,
  saveAttachmentLegacy,
  saveBulkMedicalNotes,
  saveChronicIssue,
  saveConcussionTestResults,
  saveDiagnostic,
  saveDiagnosticAttachment,
  saveDiagnosticLinks,
  saveDocument,
  saveDraftWorkersComp,
  saveDrugStock,
  saveIssue,
  saveMatchReportNotes,
  saveMatchReportScores,
  saveMedicalAlert,
  saveMedicalNote,
  saveMedicationEndDate,
  saveModificationNote,
  saveNote,
  savePlayerHasLeftClub,
  saveProcedure,
  saveProcedureAttachment,
  saveReconciledDiagnostic,
  saveRedoxReviewed,
  saveReviewedDiagnostics,
  saveTreatment,
  screenAllergyToDrug,
  screenDrugToDrug,
  searchCoding,
  searchContacts,
  searchDiagnosticTypes,
  searchDrugs,
  searchDrugsFavorites,
  searchKitMatrices,
  searchMedicalEntityAttachments,
  searchOrgAthletes,
  searchProcedureTypes,
  sendMatchNoticeEmail,
  searchEmails,
  setCoachesReportComment,
  splitDocument,
  submitWorkersComp,
  unlockAccess,
  updateAllergy,
  updateAnnotation,
  updateAthleteIssueType,
  updateAttachment,
  updateContact,
  updateCustomOppositionName,
  updateDiagnostic,
  updateExercise,
  updateFormAnswersSetLinkedIssues,
  updateGameInformation,
  updateKitMatrix,
  updateLastEvent,
  updateMedicalAlert,
  updateMedicalDocument,
  updateMedication,
  updateNflParticipationLevels,
  updateProcedure,
  updateUserEventRequest,
  uploadFile,
  uploadWithPresignedPost,
  getMatchDayTemplateData,
  getTrainingVariables,
  bulkUpdateEventRequests,
};
