// @flow

const event = {
  venue_type: {
    id: 1,
    name: 'Home',
  },
  competition: {
    competition_categories: [],
    id: 1797,
    name: 'Fest',
    format: null,
    min_substitutes: null,
    max_substitutes: null,
    min_staffs: null,
    max_staffs: null,
  },
  competition_category: null,
  opponent_squad: {
    id: 6464,
    name: 'U14',
    owner_id: 1268,
    owner_name: 'KL Toronto',
    logo_full_path:
      'https://kitman-staging.imgix.net/kitman-stock-assets/test.png?ixlib=rails-4.2.0&fit=fill&trim=off&bg=00FFFFFF&w=100&h=100',
  },
  opponent_team: null,
  organisation_format: null,
  organisation_team: null,
  organisation_fixture_rating: null,
  opponent_score: 0,
  score: 0,
  squad: {
    id: 5636,
    name: 'U14',
    owner_id: 1267,
    owner_name: 'KL Galaxy',
    logo_full_path:
      'https://kitman-staging.imgix.net/kitman-stock-assets/test.png?ixlib=rails-4.2.0&fit=fill&trim=off&bg=00FFFFFF&w=100&h=100',
  },
  status: 'awaiting_officials',
  rpe_collection_kiosk: false,
  rpe_collection_athlete: true,
  mass_input: false,
  round_number: null,
  background_color: '#b134c1',
  number_of_periods: 2,
  editable: true,
  fas_game_key: null,
  mls_game_key: null,
  game_event_id: 811144,
  disciplinary_issue: null,
  roster_submitted_by_id: null,
  match_report_submitted_by_id: null,
  external_id: null,
  tv: null,
  overwrite_subs_staffs_limit: null,
  id: 3205952,
  name: null,
  start_date: '2024-09-10T00:00:00Z',
  game_time: '2024-09-10T00:30:00Z',
  end_date: '2024-09-10T01:30:00Z',
  duration: 90,
  type: 'game_event',
  local_timezone: 'GMT',
  surface_type: null,
  surface_quality: null,
  weather: null,
  temperature: null,
  humidity: null,
  field_condition: null,
  notification_schedule: null,
  created_at: '2024-09-03T20:00:17Z',
  updated_at: '2024-09-03T20:00:18Z',
  nfl_surface_type_id: null,
  nfl_location_id: null,
  nfl_location_feed: null,
  nfl_equipment_id: null,
  nfl_surface_composition: null,
  nfl_field_type: null,
  workload_units: {},
  description: null,
  event_collection_complete: false,
  athlete_events_count: 0,
  attachments: [],
  attached_links: [],
  event_location: {
    id: 1,
    name: 'Camp Nou',
  },
  event_users: [],
  athlete_ids: [],
  visibility_ids: [],
  recurrence: {
    rule: null,
    recurring_event_id: null,
    original_start_time: null,
    rrule_instances: null,
  },
};

const gameOfficials = {
  var: {
    id: 2,
    role: 'var',
    official_id: 152182,
    official: {
      id: 152182,
      fullname: 'Mark Evans',
    },
  },
  assistant_referee_2: {
    id: 5,
    role: 'assistant_referee_2',
    official_id: 181938,
    official: {
      id: 181938,
      fullname: 'Sophia Clarke',
    },
  },
  fourth_referee: {
    id: 6,
    role: 'fourth_referee',
    official_id: 183048,
    official: {
      id: 183048,
      fullname: 'David Brooks',
    },
  },
  referee: {
    id: 1,
    role: 'referee',
    official_id: 267317,
    official: {
      id: 267317,
      fullname: 'Emily Harper',
    },
  },
  avar: {
    id: 3,
    role: 'avar',
    official_id: 267316,
    official: {
      id: 267316,
      fullname: 'Liam Turner',
    },
  },
  reserve_ar: {
    id: 7,
    role: 'reserve_ar',
    official_id: 161704,
    official: {
      id: 161704,
      fullname: 'John Doe',
    },
  },
  assistant_referee_1: {
    id: 4,
    role: 'assistant_referee_1',
    official_id: 161703,
    official: {
      id: 161703,
      fullname: 'Olivia Wright',
    },
  },
};

export default {
  event,
  gameOfficials,
};
