// @flow
import { GridRow, GridColDef } from '@mui/x-data-grid-pro';
import moment from 'moment-timezone';

const rows: GridRow = [
  {
    id: 1,
    name: 'Erling Haaland',
    status: 'Available',
    position: 'Striker',
    dob: '21 July 2000',
    team: 'Manchester City',
    goals: 9,
    assists: 1,
    previousTopScorer: true,
  },
  {
    id: 2,
    name: 'Mo Salah',
    status: 'Available',
    position: 'Midfielder',
    dob: '15 June 1992',
    team: 'Liverpool',
    goals: 7,
    assists: 4,
    previousTopScorer: true,
  },
  {
    id: 3,
    name: 'Heung-Min Son',
    status: 'Available',
    position: 'Midfielder',
    dob: '15 June 1992',
    team: 'Spurs',
    goals: 7,
    assists: 4,
    previousTopScorer: true,
  },
  {
    id: 4,
    name: 'Jarrod Bowen',
    status: 'Available',
    position: 'Midfielder',
    dob: '20 December 1996',
    team: 'West Ham',
    goals: 6,
    assists: 1,
    previousTopScorer: false,
  },
  {
    id: 5,
    name: 'Alexander Isak',
    status: 'Available',
    position: 'Striker',
    dob: '21 September 1999',
    team: 'Newcastle',
    goals: 6,
    assists: 0,
    previousTopScorer: false,
  },
  {
    id: 6,
    name: 'Hee-Chan Hwang',
    status: 'Available',
    position: 'Midfielder',
    dob: '26 January 1996',
    team: 'Wolverhampton',
    goals: 5,
    assists: 1,
    previousTopScorer: false,
  },
  {
    id: 7,
    name: 'Sandy Sutton',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Empoli',
    goals: 18,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 8,
    name: 'Young Wilkins',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 10,
    assists: 2,
    previousTopScorer: false,
  },
  {
    id: 9,
    name: 'Faith Sheppard',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 37,
    assists: 2,
    previousTopScorer: true,
  },
  {
    id: 10,
    name: 'Travis Nunez',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 36,
    assists: 2,
    previousTopScorer: false,
  },
  {
    id: 11,
    name: 'Bradley Jimenez',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Empoli',
    goals: 24,
    assists: 6,
    previousTopScorer: false,
  },
  {
    id: 12,
    name: 'Hayden Jordan',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Milan',
    goals: 29,
    assists: 4,
    previousTopScorer: true,
  },
  {
    id: 13,
    name: 'Angeline Mckinney',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Chelsea',
    goals: 8,
    assists: 5,
    previousTopScorer: true,
  },
  {
    id: 14,
    name: 'Frieda Wynn',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Chelsea',
    goals: 20,
    assists: 5,
    previousTopScorer: false,
  },
  {
    id: 15,
    name: 'Dillon Estrada',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Chelsea',
    goals: 4,
    assists: 5,
    previousTopScorer: false,
  },
  {
    id: 16,
    name: 'Georgette Sanchez',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Empoli',
    goals: 30,
    assists: 6,
    previousTopScorer: true,
  },
  {
    id: 17,
    name: 'Beth Terry',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Milan',
    goals: 6,
    assists: 5,
    previousTopScorer: false,
  },
  {
    id: 18,
    name: 'Young Melendez',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 39,
    assists: 6,
    previousTopScorer: false,
  },
  {
    id: 19,
    name: 'Etta Compton',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 30,
    assists: 5,
    previousTopScorer: true,
  },
  {
    id: 20,
    name: 'Hester Rogers',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 11,
    assists: 2,
    previousTopScorer: false,
  },
  {
    id: 21,
    name: 'Delaney Miles',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 26,
    assists: 5,
    previousTopScorer: true,
  },
  {
    id: 22,
    name: 'Angelica Huff',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 38,
    assists: 3,
    previousTopScorer: false,
  },
  {
    id: 23,
    name: 'Darla Savage',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 35,
    assists: 2,
    previousTopScorer: true,
  },
  {
    id: 24,
    name: 'Stanley Fry',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 10,
    assists: 6,
    previousTopScorer: true,
  },
  {
    id: 25,
    name: 'Medina Hinton',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 33,
    assists: 3,
    previousTopScorer: false,
  },
  {
    id: 26,
    name: 'Patty Cooke',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 5,
    assists: 5,
    previousTopScorer: false,
  },
  {
    id: 27,
    name: 'Edwards Franco',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 24,
    assists: 5,
    previousTopScorer: true,
  },
  {
    id: 28,
    name: 'Brooks Spears',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Empoli',
    goals: 1,
    assists: 3,
    previousTopScorer: false,
  },
  {
    id: 29,
    name: 'Concetta Shepard',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 8,
    assists: 3,
    previousTopScorer: true,
  },
  {
    id: 30,
    name: 'Espinoza Knox',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Liverpool',
    goals: 24,
    assists: 5,
    previousTopScorer: true,
  },
  {
    id: 31,
    name: 'Aguirre Sandoval',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Empoli',
    goals: 22,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 32,
    name: 'Buckner Garner',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Milan',
    goals: 6,
    assists: 5,
    previousTopScorer: false,
  },
  {
    id: 33,
    name: 'Chaney Slater',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 17,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 34,
    name: 'Nona Goodman',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 21,
    assists: 6,
    previousTopScorer: false,
  },
  {
    id: 35,
    name: 'Claire Reeves',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Milan',
    goals: 30,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 36,
    name: 'Clements Shepherd',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Empoli',
    goals: 5,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 37,
    name: 'Margie Bauer',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 25,
    assists: 2,
    previousTopScorer: false,
  },
  {
    id: 38,
    name: 'Gina Forbes',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Everton',
    goals: 21,
    assists: 3,
    previousTopScorer: true,
  },
  {
    id: 39,
    name: 'Eileen Burke',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 6,
    assists: 3,
    previousTopScorer: false,
  },
  {
    id: 40,
    name: 'Sherri Brown',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 3,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 41,
    name: 'Camacho Barker',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Chelsea',
    goals: 28,
    assists: 3,
    previousTopScorer: true,
  },
  {
    id: 42,
    name: 'Gertrude Middleton',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 9,
    assists: 3,
    previousTopScorer: false,
  },
  {
    id: 43,
    name: 'Jimmie Gross',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 33,
    assists: 3,
    previousTopScorer: true,
  },
  {
    id: 44,
    name: 'Johnnie Kidd',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Chelsea',
    goals: 19,
    assists: 6,
    previousTopScorer: false,
  },
  {
    id: 45,
    name: 'Trina Shaffer',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Empoli',
    goals: 39,
    assists: 3,
    previousTopScorer: true,
  },
  {
    id: 46,
    name: 'Randi Casey',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Milan',
    goals: 23,
    assists: 3,
    previousTopScorer: true,
  },
  {
    id: 47,
    name: 'Adela Payne',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 24,
    assists: 2,
    previousTopScorer: true,
  },
  {
    id: 48,
    name: 'Marsh Hopper',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 25,
    assists: 6,
    previousTopScorer: true,
  },
  {
    id: 49,
    name: 'Bonita Cooley',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 35,
    assists: 3,
    previousTopScorer: true,
  },
  {
    id: 50,
    name: 'Roslyn Vega',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 13,
    assists: 3,
    previousTopScorer: true,
  },
  {
    id: 51,
    name: 'Samantha Dalton',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Chelsea',
    goals: 32,
    assists: 6,
    previousTopScorer: false,
  },
  {
    id: 52,
    name: 'Elizabeth Hernandez',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Chelsea',
    goals: 28,
    assists: 6,
    previousTopScorer: false,
  },
  {
    id: 53,
    name: 'Lessie Osborn',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 4,
    assists: 2,
    previousTopScorer: true,
  },
  {
    id: 54,
    name: 'Mari Simpson',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 11,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 55,
    name: 'Elliott Erickson',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 36,
    assists: 2,
    previousTopScorer: true,
  },
  {
    id: 56,
    name: 'Valarie Witt',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 5,
    assists: 6,
    previousTopScorer: true,
  },
  {
    id: 57,
    name: 'Cote Villarreal',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 27,
    assists: 5,
    previousTopScorer: false,
  },
  {
    id: 58,
    name: 'Randolph Burgess',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 17,
    assists: 4,
    previousTopScorer: true,
  },
  {
    id: 59,
    name: 'Cruz Bean',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Everton',
    goals: 34,
    assists: 5,
    previousTopScorer: true,
  },
  {
    id: 60,
    name: 'Elvia Mills',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Everton',
    goals: 21,
    assists: 5,
    previousTopScorer: true,
  },
  {
    id: 61,
    name: 'Joann Howard',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Milan',
    goals: 5,
    assists: 6,
    previousTopScorer: true,
  },
  {
    id: 62,
    name: 'Janell Johnston',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 21,
    assists: 3,
    previousTopScorer: true,
  },
  {
    id: 63,
    name: 'Gilbert Vincent',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Milan',
    goals: 6,
    assists: 2,
    previousTopScorer: false,
  },
  {
    id: 64,
    name: 'Bethany Bell',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 33,
    assists: 6,
    previousTopScorer: true,
  },
  {
    id: 65,
    name: 'Linda Schultz',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Empoli',
    goals: 0,
    assists: 5,
    previousTopScorer: false,
  },
  {
    id: 66,
    name: 'Whitney Atkinson',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Liverpool',
    goals: 9,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 67,
    name: 'Kristen Chambers',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 25,
    assists: 6,
    previousTopScorer: true,
  },
  {
    id: 68,
    name: 'Kristy Rivera',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Empoli',
    goals: 9,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 69,
    name: 'Rae Cantu',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 6,
    assists: 6,
    previousTopScorer: false,
  },
  {
    id: 70,
    name: 'Fern Parks',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Everton',
    goals: 2,
    assists: 4,
    previousTopScorer: true,
  },
  {
    id: 71,
    name: 'Suarez Hensley',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Empoli',
    goals: 38,
    assists: 5,
    previousTopScorer: false,
  },
  {
    id: 72,
    name: 'Preston Bird',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 0,
    assists: 3,
    previousTopScorer: false,
  },
  {
    id: 73,
    name: 'Audra Bowman',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Chelsea',
    goals: 37,
    assists: 5,
    previousTopScorer: false,
  },
  {
    id: 74,
    name: 'Edith Dixon',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Everton',
    goals: 10,
    assists: 5,
    previousTopScorer: true,
  },
  {
    id: 75,
    name: 'Lawson David',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Liverpool',
    goals: 12,
    assists: 5,
    previousTopScorer: true,
  },
  {
    id: 76,
    name: 'Rutledge Vang',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 7,
    assists: 5,
    previousTopScorer: true,
  },
  {
    id: 77,
    name: 'Burks Ward',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Milan',
    goals: 34,
    assists: 4,
    previousTopScorer: true,
  },
  {
    id: 78,
    name: 'Mckenzie Barrera',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Liverpool',
    goals: 4,
    assists: 3,
    previousTopScorer: false,
  },
  {
    id: 79,
    name: 'Concetta Good',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Milan',
    goals: 12,
    assists: 2,
    previousTopScorer: true,
  },
  {
    id: 80,
    name: 'Justine Colon',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 4,
    assists: 6,
    previousTopScorer: true,
  },
  {
    id: 81,
    name: 'Page Ferguson',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Milan',
    goals: 11,
    assists: 3,
    previousTopScorer: false,
  },
  {
    id: 82,
    name: 'Annmarie Ellis',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 27,
    assists: 3,
    previousTopScorer: true,
  },
  {
    id: 83,
    name: 'John Snider',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Chelsea',
    goals: 6,
    assists: 6,
    previousTopScorer: false,
  },
  {
    id: 84,
    name: 'Cabrera Camacho',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 19,
    assists: 4,
    previousTopScorer: true,
  },
  {
    id: 85,
    name: 'Fuller Newton',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 38,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 86,
    name: 'Jennifer Bates',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Everton',
    goals: 29,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 87,
    name: 'Callie Maynard',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Everton',
    goals: 0,
    assists: 2,
    previousTopScorer: true,
  },
  {
    id: 88,
    name: 'Garza Melton',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Everton',
    goals: 11,
    assists: 2,
    previousTopScorer: true,
  },
  {
    id: 89,
    name: 'Vickie Fernandez',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 5,
    assists: 6,
    previousTopScorer: true,
  },
  {
    id: 90,
    name: 'Olga Gregory',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 13,
    assists: 5,
    previousTopScorer: false,
  },
  {
    id: 91,
    name: 'Molina Melendez',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Liverpool',
    goals: 33,
    assists: 6,
    previousTopScorer: false,
  },
  {
    id: 92,
    name: 'Rowe Pace',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Liverpool',
    goals: 17,
    assists: 6,
    previousTopScorer: true,
  },
  {
    id: 93,
    name: 'Marsha Garza',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Everton',
    goals: 35,
    assists: 3,
    previousTopScorer: true,
  },
  {
    id: 94,
    name: 'Chavez Cunningham',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 27,
    assists: 6,
    previousTopScorer: false,
  },
  {
    id: 95,
    name: 'Bond Ford',
    status: 'Available',
    position: 'midfielder',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 40,
    assists: 6,
    previousTopScorer: true,
  },
  {
    id: 96,
    name: 'Latasha Nieves',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Chelsea',
    goals: 39,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 97,
    name: 'Jeanne Rush',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Chelsea',
    goals: 18,
    assists: 4,
    previousTopScorer: false,
  },
  {
    id: 98,
    name: 'Terri Tyler',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Empoli',
    goals: 26,
    assists: 4,
    previousTopScorer: true,
  },
  {
    id: 99,
    name: 'Skinner Harrell',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 26,
    assists: 5,
    previousTopScorer: false,
  },
  {
    id: 100,
    name: 'Harrison Richard',
    status: 'Available',
    position: 'forward',
    dob: '15 June 1992',
    team: 'Roma',
    goals: 14,
    assists: 6,
    previousTopScorer: false,
  },
  {
    id: 101,
    name: 'Griffin Gomez',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 26,
    assists: 5,
    previousTopScorer: false,
  },
  {
    id: 102,
    name: 'Singleton Tran',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Juventus',
    goals: 7,
    assists: 6,
    previousTopScorer: true,
  },
  {
    id: 103,
    name: 'Sonia Booth',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Liverpool',
    goals: 8,
    assists: 2,
    previousTopScorer: true,
  },
  {
    id: 104,
    name: 'Bobbi Riley',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 0,
    assists: 3,
    previousTopScorer: false,
  },
  {
    id: 105,
    name: 'Gill Romero',
    status: 'Available',
    position: 'goalkeeper',
    dob: '15 June 1992',
    team: 'Chelsea',
    goals: 21,
    assists: 2,
    previousTopScorer: true,
  },
  {
    id: 106,
    name: 'Chase Herrera',
    status: 'Available',
    position: 'defender',
    dob: '15 June 1992',
    team: 'Machester United',
    goals: 27,
    assists: 6,
    previousTopScorer: false,
  },
];
const columns: GridColDef[] = [
  {
    field: 'name',
    headerName: 'Name',
    width: 150,
    editable: true,
  },
  {
    field: 'status',
    headerName: 'Injury Status',
    flex: 1,
    filterable: false,
  },
  {
    field: 'position',
    headerName: 'Position',
    flex: 1,
  },
  {
    field: 'dob',
    headerName: 'Date of Birth',
    flex: 1,
    // type: 'date',// todo: (more investigation) this will mess up the date filter
    valueGetter: (params) => moment.utc(params?.value),
    valueFormatter: (params) => {
      return moment.utc(params?.value).format('DD/MM/YYYY');
    },
  },
  { field: 'team', headerName: 'Team', flex: 1 },
  { field: 'goals', headerName: 'Goals', flex: 1 },
  { field: 'assists', headerName: 'Assists', flex: 1 },
  {
    field: 'previousTopScorer',
    headerName: 'Previous winner',
    flex: 1,
    type: 'boolean',
    filterable: true,
  },
];

export { rows, columns };
